package interfaces;

import java.awt.Color;
import java.time.LocalDateTime;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

public class Administrador extends javax.swing.JFrame {

    //Interruptor de Botones de menu para cambiar animacion
    int encendido_usuario = 1;
    int encendido_equipo = 0;
    int encendido_reporte = 0;
    int encendido_inventario = 0;
    
    //Variables estaticas que pasan entre interfaces
    public static String tipo = "";
    public static String nombreA = "";
    public static String usuario = "";

    //Variables para obtener posicion(x,y) de la ventana en la pantalla
    int mouseX, mouseY;
    
    
     /*Fecha y Hora*/
    LocalDateTime fecha = LocalDateTime.now();

    int annio = fecha.getYear();
    int mes = fecha.getMonthValue();
    int dia = fecha.getDayOfMonth();
    int hora = fecha.getHour();
    int minutos = fecha.getMinute();
    int segundo = fecha.getSecond();


    public Administrador() {

        
        tipo = Login.tipo_permiso;
        nombreA = Login.nombre_apellido;
        usuario = Login.usuario_nombre;
        
        initComponents();
        setTitle("Menu Administrador");
        setSize(900, 720);
        setLocationRelativeTo(null);
        setResizable(false);
        
        label_usuario_nombre.setText(Administrador.nombreA);
        label_equipo_nombre.setText(Administrador.nombreA);
        label_reporte_nombre.setText(Administrador.nombreA);
        label_inventario_nombre.setText(Administrador.nombreA);

        p_menuA_usuarios.setVisible(true);
        p_menuA_equipos.setVisible(false);
        p_menuA_reportes.setVisible(false);
        p_menuA_inventario.setVisible(false);
        
        
        //Hora y Fecha de la interfaz
        u_fecha.setText(dia + " / " + mes + " / " + annio);
        u_hora.setText(hora + ":" + minutos + "PM");
        
        e_fecha.setText(dia + " / " + mes + " / " + annio);
        e_hora.setText(hora + ":" + minutos + "PM");
        
        r_fecha.setText(dia + " / " + mes + " / " + annio);
        r_hora.setText(hora + ":" + minutos + "PM");
        
        i_fecha.setText(dia + " / " + mes + " / " + annio);
        i_hora.setText(hora + ":" + minutos + "PM");
        
       p_menu_b_usuarios.setBackground(new Color(0, 70, 160));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_menuA_reportes = new prueba_diseño.PanelRound();
        e_reporte_menu_reporte = new javax.swing.JLabel();
        p_menu_b_crear_reporte = new prueba_diseño.PanelRound();
        j_e_icon_reporte = new javax.swing.JLabel();
        e_modificar_menu_reporte = new javax.swing.JLabel();
        p_menu_b_modificar_reporte = new prueba_diseño.PanelRound();
        j_e_icon_modificar_reporte = new javax.swing.JLabel();
        e_estadistica_menu_reporte = new javax.swing.JLabel();
        p_menu_b_estadistica = new prueba_diseño.PanelRound();
        j_e_icon_estadistica = new javax.swing.JLabel();
        e_listar_reportes_menu_reporte = new javax.swing.JLabel();
        p_menu_b_lista_reporte = new prueba_diseño.PanelRound();
        j_e_icon_lista_reporte = new javax.swing.JLabel();
        i_calendario_menu_reporte = new javax.swing.JLabel();
        r_fecha = new javax.swing.JLabel();
        r_hora = new javax.swing.JLabel();
        i_usuario_menu_reporte = new javax.swing.JLabel();
        label_reporte_nombre = new javax.swing.JLabel();
        p_menuA_usuarios = new prueba_diseño.PanelRound();
        p_menu_b_crearursuario = new prueba_diseño.PanelRound();
        j_e_icon_crear_usuarios = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_menu_b_crear_usuario_equipo = new prueba_diseño.PanelRound();
        j_e_icon_crear_usuario_equipo = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        p_menu_b_modificar_usuario = new prueba_diseño.PanelRound();
        j_e_icon_modificar_usuarios = new javax.swing.JLabel();
        b_usuario_modificar_evento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_menu_b_lista_usuario = new prueba_diseño.PanelRound();
        j_e_icon_crear_usuarios2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_usuario_nombre = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        u_fecha = new javax.swing.JLabel();
        u_hora = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        b_usuario_crear_evento = new javax.swing.JLabel();
        b_usuario_equipo_evento = new javax.swing.JLabel();
        b_usuario_lista_evento = new javax.swing.JLabel();
        p_menuA_inventario = new prueba_diseño.PanelRound();
        e_ingresar_articulo = new javax.swing.JLabel();
        p_menu_b_ingresar_articulo = new prueba_diseño.PanelRound();
        j_e_icon_ingresar_articulo = new javax.swing.JLabel();
        e_modificar_articulo = new javax.swing.JLabel();
        p_menu_b_modificar_articulo = new prueba_diseño.PanelRound();
        j_e_icon_modificar_articulos = new javax.swing.JLabel();
        e_listar_articulo = new javax.swing.JLabel();
        p_menu_b_lista_articulos = new prueba_diseño.PanelRound();
        j_e_icon_lista_articulo = new javax.swing.JLabel();
        i_fecha = new javax.swing.JLabel();
        i_hora = new javax.swing.JLabel();
        label_inventario_nombre = new javax.swing.JLabel();
        i_usuario = new javax.swing.JLabel();
        i_calendario = new javax.swing.JLabel();
        p_menu_barra = new prueba_diseño.PanelRound();
        p_menu_b_usuarios = new prueba_diseño.PanelRound();
        b_menu_administrador_usuarios = new javax.swing.JLabel();
        j_e_icon_menu_usuario = new javax.swing.JLabel();
        p_menu_b_equipos = new prueba_diseño.PanelRound();
        b_menu_administrador_equipos = new javax.swing.JLabel();
        j_e_icon_menu_equipo = new javax.swing.JLabel();
        p_menu_b_reportes = new prueba_diseño.PanelRound();
        j_e_icon_menu_reporte = new javax.swing.JLabel();
        b_menu_administrador_reportes = new javax.swing.JLabel();
        p_menu_b_inventarios = new prueba_diseño.PanelRound();
        j_e_icon_menu_inventario = new javax.swing.JLabel();
        b_menu_administrador_inventario = new javax.swing.JLabel();
        p_menu_b_manual = new prueba_diseño.PanelRound();
        btn_manual = new javax.swing.JLabel();
        j_e_icon_menu_manual = new javax.swing.JLabel();
        p_menu_b_salir = new prueba_diseño.PanelRound();
        b_menu_administrador_salir = new javax.swing.JLabel();
        j_e_icon_menu_salir = new javax.swing.JLabel();
        j_e_icon_menu_logo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        p_menuA_equipos = new prueba_diseño.PanelRound();
        p_menu_b_registrar_equipo = new prueba_diseño.PanelRound();
        j_e_icon_registrar_equipos = new javax.swing.JLabel();
        p_menu_b_modificar_equipo = new prueba_diseño.PanelRound();
        j_e_icon_modificar_equipo = new javax.swing.JLabel();
        p_menu_b_tipos_equipos = new prueba_diseño.PanelRound();
        j_e_icon_registrar_tipos = new javax.swing.JLabel();
        p_menu_b_lista_equipo = new prueba_diseño.PanelRound();
        j_e_icon_lista_equipo = new javax.swing.JLabel();
        e_lista_menu_equipos = new javax.swing.JLabel();
        e_modificar_menu_equipos = new javax.swing.JLabel();
        e_registrar_menu_equipos = new javax.swing.JLabel();
        e_fecha = new javax.swing.JLabel();
        e_hora = new javax.swing.JLabel();
        label_equipo_nombre = new javax.swing.JLabel();
        i_usuario_menu_equipos = new javax.swing.JLabel();
        i_calendario_menu_equipos = new javax.swing.JLabel();
        e_registro_tipo_menu_equipos = new javax.swing.JLabel();
        barra_mover2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menuA_reportes.setBackground(new java.awt.Color(234, 234, 234));
        p_menuA_reportes.setRoundBottomLeft(50);
        p_menuA_reportes.setRoundBottomRight(50);
        p_menuA_reportes.setRoundTopLeft(50);
        p_menuA_reportes.setRoundTopRight(50);
        p_menuA_reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_reporte_menu_reporte.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_reporte_menu_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_reporte_menu_reporte.setText("Reporte ");
        p_menuA_reportes.add(e_reporte_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, -1));

        p_menu_b_crear_reporte.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_crear_reporte.setRoundBottomLeft(50);
        p_menu_b_crear_reporte.setRoundBottomRight(50);
        p_menu_b_crear_reporte.setRoundTopLeft(50);
        p_menu_b_crear_reporte.setRoundTopRight(50);
        p_menu_b_crear_reporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/formulario-de-llenado.png"))); // NOI18N
        j_e_icon_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_reporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_reporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_reporteMouseExited(evt);
            }
        });
        p_menu_b_crear_reporte.add(j_e_icon_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_crear_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 170));

        e_modificar_menu_reporte.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_modificar_menu_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_modificar_menu_reporte.setText("Modificar");
        p_menuA_reportes.add(e_modificar_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 170, -1));

        p_menu_b_modificar_reporte.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_modificar_reporte.setRoundBottomLeft(50);
        p_menu_b_modificar_reporte.setRoundBottomRight(50);
        p_menu_b_modificar_reporte.setRoundTopLeft(50);
        p_menu_b_modificar_reporte.setRoundTopRight(50);
        p_menu_b_modificar_reporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_modificar_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_modificar_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/eliminar.png"))); // NOI18N
        j_e_icon_modificar_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_reporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_reporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_reporteMouseExited(evt);
            }
        });
        p_menu_b_modificar_reporte.add(j_e_icon_modificar_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_modificar_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 170, 170));

        e_estadistica_menu_reporte.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_estadistica_menu_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_estadistica_menu_reporte.setText("Estadísticas");
        p_menuA_reportes.add(e_estadistica_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 170, -1));

        p_menu_b_estadistica.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_estadistica.setRoundBottomLeft(50);
        p_menu_b_estadistica.setRoundBottomRight(50);
        p_menu_b_estadistica.setRoundTopLeft(50);
        p_menu_b_estadistica.setRoundTopRight(50);
        p_menu_b_estadistica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_estadistica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_estadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/grafico-de-barras.png"))); // NOI18N
        j_e_icon_estadistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_estadisticaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_estadisticaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_estadisticaMouseExited(evt);
            }
        });
        p_menu_b_estadistica.add(j_e_icon_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 170));

        e_listar_reportes_menu_reporte.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_listar_reportes_menu_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_listar_reportes_menu_reporte.setText("Lista");
        p_menuA_reportes.add(e_listar_reportes_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 170, -1));

        p_menu_b_lista_reporte.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_lista_reporte.setRoundBottomLeft(50);
        p_menu_b_lista_reporte.setRoundBottomRight(50);
        p_menu_b_lista_reporte.setRoundTopLeft(50);
        p_menu_b_lista_reporte.setRoundTopRight(50);
        p_menu_b_lista_reporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/gestion-de-proyectos.png"))); // NOI18N
        j_e_icon_lista_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_reporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_reporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_reporteMouseExited(evt);
            }
        });
        p_menu_b_lista_reporte.add(j_e_icon_lista_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_lista_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 170, 170));

        i_calendario_menu_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_calendario_menu_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario-reloj (2).png"))); // NOI18N
        p_menuA_reportes.add(i_calendario_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 9, 40, 40));

        r_fecha.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        r_fecha.setText("00/00/0000");
        p_menuA_reportes.add(r_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, 80, -1));

        r_hora.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        r_hora.setText("00:00 APM");
        p_menuA_reportes.add(r_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, -1));

        i_usuario_menu_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_usuario_menu_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/picpersonas-llenas.png"))); // NOI18N
        p_menuA_reportes.add(i_usuario_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 40));

        label_reporte_nombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        p_menuA_reportes.add(label_reporte_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 30));

        jPanel1.add(p_menuA_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        p_menuA_usuarios.setBackground(new java.awt.Color(234, 234, 234));
        p_menuA_usuarios.setRoundBottomLeft(50);
        p_menuA_usuarios.setRoundBottomRight(50);
        p_menuA_usuarios.setRoundTopLeft(50);
        p_menuA_usuarios.setRoundTopRight(50);
        p_menuA_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_b_crearursuario.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_crearursuario.setRoundBottomLeft(50);
        p_menu_b_crearursuario.setRoundBottomRight(50);
        p_menu_b_crearursuario.setRoundTopLeft(50);
        p_menu_b_crearursuario.setRoundTopRight(50);
        p_menu_b_crearursuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_crear_usuarios.setBackground(new java.awt.Color(225, 225, 225));
        j_e_icon_crear_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_crear_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/agregar-usuario (5).png"))); // NOI18N
        j_e_icon_crear_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuariosMouseExited(evt);
            }
        });
        p_menu_b_crearursuario.add(j_e_icon_crear_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 160));

        p_menuA_usuarios.add(p_menu_b_crearursuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 160));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear ");
        p_menuA_usuarios.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, -1));

        p_menu_b_crear_usuario_equipo.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_crear_usuario_equipo.setRoundBottomLeft(50);
        p_menu_b_crear_usuario_equipo.setRoundBottomRight(50);
        p_menu_b_crear_usuario_equipo.setRoundTopLeft(50);
        p_menu_b_crear_usuario_equipo.setRoundTopRight(50);
        p_menu_b_crear_usuario_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_crear_usuario_equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_crear_usuario_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/programador.png"))); // NOI18N
        j_e_icon_crear_usuario_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuario_equipoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuario_equipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuario_equipoMouseExited(evt);
            }
        });
        p_menu_b_crear_usuario_equipo.add(j_e_icon_crear_usuario_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 160));

        p_menuA_usuarios.add(p_menu_b_crear_usuario_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 160, 160));

        jLabel24.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Usuario de Equipo");
        p_menuA_usuarios.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 170, -1));

        p_menu_b_modificar_usuario.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_modificar_usuario.setRoundBottomLeft(50);
        p_menu_b_modificar_usuario.setRoundBottomRight(50);
        p_menu_b_modificar_usuario.setRoundTopLeft(50);
        p_menu_b_modificar_usuario.setRoundTopRight(50);
        p_menu_b_modificar_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_modificar_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_modificar_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/editar.png"))); // NOI18N
        j_e_icon_modificar_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_usuariosMouseExited(evt);
            }
        });
        p_menu_b_modificar_usuario.add(j_e_icon_modificar_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 160));
        p_menu_b_modificar_usuario.add(b_usuario_modificar_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 190));

        p_menuA_usuarios.add(p_menu_b_modificar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, 160));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modificar ");
        p_menuA_usuarios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 170, -1));

        p_menu_b_lista_usuario.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_lista_usuario.setRoundBottomLeft(50);
        p_menu_b_lista_usuario.setRoundBottomRight(50);
        p_menu_b_lista_usuario.setRoundTopLeft(50);
        p_menu_b_lista_usuario.setRoundTopRight(50);
        p_menu_b_lista_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_crear_usuarios2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_crear_usuarios2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/cliente.png"))); // NOI18N
        j_e_icon_crear_usuarios2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuarios2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuarios2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_crear_usuarios2MouseExited(evt);
            }
        });
        p_menu_b_lista_usuario.add(j_e_icon_crear_usuarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 160));

        p_menuA_usuarios.add(p_menu_b_lista_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 160, 160));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lista");
        p_menuA_usuarios.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 170, -1));

        label_usuario_nombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        p_menuA_usuarios.add(label_usuario_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 30));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/picpersonas-llenas.png"))); // NOI18N
        p_menuA_usuarios.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 40));

        u_fecha.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        u_fecha.setText("00/00/0000");
        p_menuA_usuarios.add(u_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, 80, -1));

        u_hora.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        u_hora.setText("00:00 APM");
        p_menuA_usuarios.add(u_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario-reloj (2).png"))); // NOI18N
        p_menuA_usuarios.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 9, 40, 40));
        p_menuA_usuarios.add(b_usuario_crear_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 180));
        p_menuA_usuarios.add(b_usuario_equipo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 160, 180));
        p_menuA_usuarios.add(b_usuario_lista_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 160, 180));

        jPanel1.add(p_menuA_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        p_menuA_inventario.setBackground(new java.awt.Color(234, 234, 234));
        p_menuA_inventario.setRoundBottomLeft(50);
        p_menuA_inventario.setRoundBottomRight(50);
        p_menuA_inventario.setRoundTopLeft(50);
        p_menuA_inventario.setRoundTopRight(50);
        p_menuA_inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_ingresar_articulo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_ingresar_articulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_ingresar_articulo.setText("Ingresar Articulo");
        p_menuA_inventario.add(e_ingresar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, -1));

        p_menu_b_ingresar_articulo.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_ingresar_articulo.setRoundBottomLeft(50);
        p_menu_b_ingresar_articulo.setRoundBottomRight(50);
        p_menu_b_ingresar_articulo.setRoundTopLeft(50);
        p_menu_b_ingresar_articulo.setRoundTopRight(50);
        p_menu_b_ingresar_articulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_ingresar_articulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_ingresar_articulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/inventario.png"))); // NOI18N
        j_e_icon_ingresar_articulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_ingresar_articuloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_ingresar_articuloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_ingresar_articuloMouseExited(evt);
            }
        });
        p_menu_b_ingresar_articulo.add(j_e_icon_ingresar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_inventario.add(p_menu_b_ingresar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 170));

        e_modificar_articulo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_modificar_articulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_modificar_articulo.setText("Modificar Articulo");
        p_menuA_inventario.add(e_modificar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 170, -1));

        p_menu_b_modificar_articulo.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_modificar_articulo.setRoundBottomLeft(50);
        p_menu_b_modificar_articulo.setRoundBottomRight(50);
        p_menu_b_modificar_articulo.setRoundTopLeft(50);
        p_menu_b_modificar_articulo.setRoundTopRight(50);
        p_menu_b_modificar_articulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_modificar_articulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_modificar_articulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/la-gestion-del-inventario.png"))); // NOI18N
        j_e_icon_modificar_articulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_articulosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_articulosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_articulosMouseExited(evt);
            }
        });
        p_menu_b_modificar_articulo.add(j_e_icon_modificar_articulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_inventario.add(p_menu_b_modificar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 170, 170));

        e_listar_articulo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_listar_articulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_listar_articulo.setText("Listar Articulos");
        p_menuA_inventario.add(e_listar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 170, -1));

        p_menu_b_lista_articulos.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_lista_articulos.setRoundBottomLeft(50);
        p_menu_b_lista_articulos.setRoundBottomRight(50);
        p_menu_b_lista_articulos.setRoundTopLeft(50);
        p_menu_b_lista_articulos.setRoundTopRight(50);
        p_menu_b_lista_articulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_articulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_articulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/inventario (1).png"))); // NOI18N
        j_e_icon_lista_articulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_articuloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_articuloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_articuloMouseExited(evt);
            }
        });
        p_menu_b_lista_articulos.add(j_e_icon_lista_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_inventario.add(p_menu_b_lista_articulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, 170));

        i_fecha.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        i_fecha.setText("00/00/0000");
        p_menuA_inventario.add(i_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, 80, -1));

        i_hora.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        i_hora.setText("00:00 APM");
        p_menuA_inventario.add(i_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, -1));

        label_inventario_nombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        p_menuA_inventario.add(label_inventario_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 30));

        i_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/picpersonas-llenas.png"))); // NOI18N
        p_menuA_inventario.add(i_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 40));

        i_calendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario-reloj (2).png"))); // NOI18N
        p_menuA_inventario.add(i_calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 9, 40, 40));

        jPanel1.add(p_menuA_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        p_menu_barra.setBackground(new java.awt.Color(36, 22, 74));
        p_menu_barra.setRoundBottomLeft(50);
        p_menu_barra.setRoundBottomRight(50);
        p_menu_barra.setRoundTopLeft(50);
        p_menu_barra.setRoundTopRight(50);
        p_menu_barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_b_usuarios.setBackground(new java.awt.Color(0, 102, 102));
        p_menu_b_usuarios.setRoundBottomLeft(50);
        p_menu_b_usuarios.setRoundBottomRight(50);
        p_menu_b_usuarios.setRoundTopLeft(50);
        p_menu_b_usuarios.setRoundTopRight(50);
        p_menu_b_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_menu_administrador_usuarios.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_menu_administrador_usuarios.setForeground(new java.awt.Color(234, 234, 234));
        b_menu_administrador_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_usuarios.setText("USUARIOS");
        b_menu_administrador_usuarios.setPreferredSize(new java.awt.Dimension(54, 17));
        b_menu_administrador_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_usuariosMouseExited(evt);
            }
        });
        p_menu_b_usuarios.add(b_menu_administrador_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        j_e_icon_menu_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        j_e_icon_menu_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/usuario.png"))); // NOI18N
        p_menu_b_usuarios.add(j_e_icon_menu_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 40));

        p_menu_barra.add(p_menu_b_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 50));

        p_menu_b_equipos.setBackground(new java.awt.Color(0, 102, 102));
        p_menu_b_equipos.setRoundBottomLeft(50);
        p_menu_b_equipos.setRoundBottomRight(50);
        p_menu_b_equipos.setRoundTopLeft(50);
        p_menu_b_equipos.setRoundTopRight(50);
        p_menu_b_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_menu_b_equiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_menu_b_equiposMouseExited(evt);
            }
        });
        p_menu_b_equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_menu_administrador_equipos.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_menu_administrador_equipos.setForeground(new java.awt.Color(234, 234, 234));
        b_menu_administrador_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_equipos.setText("EQUIPOS");
        b_menu_administrador_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_equiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_equiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_equiposMouseExited(evt);
            }
        });
        p_menu_b_equipos.add(b_menu_administrador_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        j_e_icon_menu_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/equipo-de-computadora (1).png"))); // NOI18N
        p_menu_b_equipos.add(j_e_icon_menu_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 40, 40));

        p_menu_barra.add(p_menu_b_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 50));

        p_menu_b_reportes.setBackground(new java.awt.Color(0, 102, 102));
        p_menu_b_reportes.setRoundBottomLeft(50);
        p_menu_b_reportes.setRoundBottomRight(50);
        p_menu_b_reportes.setRoundTopLeft(50);
        p_menu_b_reportes.setRoundTopRight(50);
        p_menu_b_reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_menu_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/portapapeles.png"))); // NOI18N
        p_menu_b_reportes.add(j_e_icon_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 40));

        b_menu_administrador_reportes.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_menu_administrador_reportes.setForeground(new java.awt.Color(234, 234, 234));
        b_menu_administrador_reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_reportes.setText("REPORTES");
        b_menu_administrador_reportes.setPreferredSize(new java.awt.Dimension(54, 17));
        b_menu_administrador_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_reportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_reportesMouseExited(evt);
            }
        });
        p_menu_b_reportes.add(b_menu_administrador_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        p_menu_barra.add(p_menu_b_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 50));

        p_menu_b_inventarios.setBackground(new java.awt.Color(0, 102, 102));
        p_menu_b_inventarios.setRoundBottomLeft(50);
        p_menu_b_inventarios.setRoundBottomRight(50);
        p_menu_b_inventarios.setRoundTopLeft(50);
        p_menu_b_inventarios.setRoundTopRight(50);
        p_menu_b_inventarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_menu_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/caja.png"))); // NOI18N
        p_menu_b_inventarios.add(j_e_icon_menu_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 40));

        b_menu_administrador_inventario.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_menu_administrador_inventario.setForeground(new java.awt.Color(234, 234, 234));
        b_menu_administrador_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_inventario.setText("   INVENTARIO");
        b_menu_administrador_inventario.setPreferredSize(new java.awt.Dimension(54, 17));
        b_menu_administrador_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_inventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_inventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_inventarioMouseExited(evt);
            }
        });
        p_menu_b_inventarios.add(b_menu_administrador_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        p_menu_barra.add(p_menu_b_inventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, 50));

        p_menu_b_manual.setRoundBottomLeft(50);
        p_menu_b_manual.setRoundBottomRight(50);
        p_menu_b_manual.setRoundTopLeft(50);
        p_menu_b_manual.setRoundTopRight(50);
        p_menu_b_manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_menu_b_manualMouseClicked(evt);
            }
        });
        p_menu_b_manual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_manual.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        btn_manual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_manual.setText(" MANUAL");
        btn_manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manualMouseExited(evt);
            }
        });
        p_menu_b_manual.add(btn_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        j_e_icon_menu_manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/instrucciones.png"))); // NOI18N
        p_menu_b_manual.add(j_e_icon_menu_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        p_menu_barra.add(p_menu_b_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 140, 50));

        p_menu_b_salir.setRoundBottomLeft(50);
        p_menu_b_salir.setRoundBottomRight(50);
        p_menu_b_salir.setRoundTopLeft(50);
        p_menu_b_salir.setRoundTopRight(50);
        p_menu_b_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_menu_administrador_salir.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        b_menu_administrador_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_salir.setText("   SALIR");
        b_menu_administrador_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_salirMouseExited(evt);
            }
        });
        p_menu_b_salir.add(b_menu_administrador_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        j_e_icon_menu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/salida.png"))); // NOI18N
        p_menu_b_salir.add(j_e_icon_menu_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        p_menu_barra.add(p_menu_b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 120, 50));

        j_e_icon_menu_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_menu_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/cerdo.png"))); // NOI18N
        p_menu_barra.add(j_e_icon_menu_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 70));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Administrador");
        p_menu_barra.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 30));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sicot");
        p_menu_barra.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 60));

        jPanel1.add(p_menu_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 650));

        p_menuA_equipos.setBackground(new java.awt.Color(234, 234, 234));
        p_menuA_equipos.setRoundBottomLeft(50);
        p_menuA_equipos.setRoundBottomRight(50);
        p_menuA_equipos.setRoundTopLeft(50);
        p_menuA_equipos.setRoundTopRight(50);
        p_menuA_equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_b_registrar_equipo.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_registrar_equipo.setRoundBottomLeft(50);
        p_menu_b_registrar_equipo.setRoundBottomRight(50);
        p_menu_b_registrar_equipo.setRoundTopLeft(50);
        p_menu_b_registrar_equipo.setRoundTopRight(50);
        p_menu_b_registrar_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_registrar_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_registrar_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/agregar.png"))); // NOI18N
        j_e_icon_registrar_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_equiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_equiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_equiposMouseExited(evt);
            }
        });
        p_menu_b_registrar_equipo.add(j_e_icon_registrar_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_registrar_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 170));

        p_menu_b_modificar_equipo.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_modificar_equipo.setRoundBottomLeft(50);
        p_menu_b_modificar_equipo.setRoundBottomRight(50);
        p_menu_b_modificar_equipo.setRoundTopLeft(50);
        p_menu_b_modificar_equipo.setRoundTopRight(50);
        p_menu_b_modificar_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_modificar_equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_modificar_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/configuracion.png"))); // NOI18N
        j_e_icon_modificar_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_equipoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_equipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_equipoMouseExited(evt);
            }
        });
        p_menu_b_modificar_equipo.add(j_e_icon_modificar_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_modificar_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 90, 170, 170));

        p_menu_b_tipos_equipos.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_tipos_equipos.setRoundBottomLeft(50);
        p_menu_b_tipos_equipos.setRoundBottomRight(50);
        p_menu_b_tipos_equipos.setRoundTopLeft(50);
        p_menu_b_tipos_equipos.setRoundTopRight(50);
        p_menu_b_tipos_equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_registrar_tipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_registrar_tipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu_equipos/nube (3).png"))); // NOI18N
        j_e_icon_registrar_tipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_tiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_tiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_tiposMouseExited(evt);
            }
        });
        p_menu_b_tipos_equipos.add(j_e_icon_registrar_tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_tipos_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 170));

        p_menu_b_lista_equipo.setBackground(new java.awt.Color(225, 225, 225));
        p_menu_b_lista_equipo.setRoundBottomLeft(50);
        p_menu_b_lista_equipo.setRoundBottomRight(50);
        p_menu_b_lista_equipo.setRoundTopLeft(50);
        p_menu_b_lista_equipo.setRoundTopRight(50);
        p_menu_b_lista_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/computadora-personal.png"))); // NOI18N
        j_e_icon_lista_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipoMouseExited(evt);
            }
        });
        p_menu_b_lista_equipo.add(j_e_icon_lista_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_lista_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, 170));

        e_lista_menu_equipos.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_lista_menu_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_lista_menu_equipos.setText("Lista");
        p_menuA_equipos.add(e_lista_menu_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 170, -1));

        e_modificar_menu_equipos.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_modificar_menu_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_modificar_menu_equipos.setText("Modificar");
        p_menuA_equipos.add(e_modificar_menu_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 170, -1));

        e_registrar_menu_equipos.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_registrar_menu_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_registrar_menu_equipos.setText("Registrar ");
        p_menuA_equipos.add(e_registrar_menu_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, -1));

        e_fecha.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        e_fecha.setText("00/00/0000");
        p_menuA_equipos.add(e_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, 80, -1));

        e_hora.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        e_hora.setText("00:00 APM");
        p_menuA_equipos.add(e_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, -1));

        label_equipo_nombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        p_menuA_equipos.add(label_equipo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 30));

        i_usuario_menu_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_usuario_menu_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/picpersonas-llenas.png"))); // NOI18N
        p_menuA_equipos.add(i_usuario_menu_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 40));

        i_calendario_menu_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_calendario_menu_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario-reloj (2).png"))); // NOI18N
        p_menuA_equipos.add(i_calendario_menu_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 9, 40, 40));

        e_registro_tipo_menu_equipos.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        e_registro_tipo_menu_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_registro_tipo_menu_equipos.setText("Registrar tipos");
        p_menuA_equipos.add(e_registro_tipo_menu_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 170, -1));

        jPanel1.add(p_menuA_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        barra_mover2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_mover2MouseDragged(evt);
            }
        });
        barra_mover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_mover2MousePressed(evt);
            }
        });
        jPanel1.add(barra_mover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_menu_administrador_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_usuariosMouseEntered
        //Cambio de color al hacer focus al boton "USARIO"
        if (encendido_usuario == 0) {
            p_menu_b_usuarios.setBackground(new Color(0, 65, 75));
        } else {

        }
    }//GEN-LAST:event_b_menu_administrador_usuariosMouseEntered

    private void b_menu_administrador_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_usuariosMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton "USUARIO"
        if (encendido_usuario == 0) {
            p_menu_b_usuarios.setBackground(new Color(0, 102, 102));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_usuariosMouseExited

    private void p_menu_b_equiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_menu_b_equiposMouseEntered
    }//GEN-LAST:event_p_menu_b_equiposMouseEntered

    private void b_menu_administrador_equiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_equiposMouseEntered
        // Cambio de color al hacer focus al boton "EQUIPO" del menu del adminitrador
        if (encendido_equipo == 0) {
            p_menu_b_equipos.setBackground(new Color(0, 65, 75));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_equiposMouseEntered

    private void p_menu_b_equiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_menu_b_equiposMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_menu_b_equiposMouseExited

    private void b_menu_administrador_equiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_equiposMouseExited
// volver al color original despues haber pasado el raton, por encima del boton de "EQUIPO"
        if (encendido_equipo == 0) {
            p_menu_b_equipos.setBackground(new Color(0, 102, 102));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_equiposMouseExited

    private void b_menu_administrador_reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_reportesMouseEntered
        // Cambio de color al hacer focus al boton "REPORTE" del menu del adminitrador
        if (encendido_reporte == 0) {
            p_menu_b_reportes.setBackground(new Color(0, 65, 75));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_reportesMouseEntered

    private void b_menu_administrador_reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_reportesMouseExited
// volver al color original despues haber pasado el raton, por encima del boton de "REPORTE"
        if (encendido_reporte == 0) {
            p_menu_b_reportes.setBackground(new Color(0, 102, 102));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_reportesMouseExited

    private void b_menu_administrador_inventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_inventarioMouseEntered
        // Cambio de color al hacer focus al boton "INVENTARIO" del menu del adminitrador
        if (encendido_inventario == 0) {
            p_menu_b_inventarios.setBackground(new Color(0, 65, 75));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_inventarioMouseEntered

    private void b_menu_administrador_inventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_inventarioMouseExited
// volver al color original despues haber pasado el raton, por encima del boton de "INVENTRIO"
        if (encendido_inventario == 0) {
            p_menu_b_inventarios.setBackground(new Color(0, 102, 102));;
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_inventarioMouseExited

    private void p_menu_b_manualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_menu_b_manualMouseClicked
    }//GEN-LAST:event_p_menu_b_manualMouseClicked

    private void btn_manualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseEntered
        // Cambio de color al hacer focus al boton "MANUAL" del menu del adminitrador
        p_menu_b_manual.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_manualMouseEntered

    private void btn_manualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "MANUAL"
        p_menu_b_manual.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_btn_manualMouseExited

    private void b_menu_administrador_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_salirMouseEntered
        // Cambio de color al hacer focus al boton "SALIR" del menu del adminitrador
        p_menu_b_salir.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_b_menu_administrador_salirMouseEntered

    private void b_menu_administrador_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_salirMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "SALIR"
        p_menu_b_salir.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_b_menu_administrador_salirMouseExited

    private void j_e_icon_crear_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuariosMouseEntered
        // Cambio de color al hacer focus al boton "CREAR USUARIO" del menu del USUARIO
        p_menu_b_crearursuario.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_crear_usuariosMouseEntered

    private void j_e_icon_crear_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuariosMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "CREAR USUARIO"
        p_menu_b_crearursuario.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_crear_usuariosMouseExited

    private void j_e_icon_crear_usuario_equipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuario_equipoMouseEntered
        // Cambio de color al hacer focus al boton "CREAR USUARIO DE EQUIPO" del menu del USUARIO
        p_menu_b_crear_usuario_equipo.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_crear_usuario_equipoMouseEntered

    private void j_e_icon_crear_usuario_equipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuario_equipoMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "CREAR USUARIO DE EQUIPO"
        p_menu_b_crear_usuario_equipo.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_crear_usuario_equipoMouseExited

    private void j_e_icon_modificar_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_usuariosMouseEntered
        // Cambio de color al hacer focus al boton "MODIFICAR USUARIO" del menu del USUARIO
        p_menu_b_modificar_usuario.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_modificar_usuariosMouseEntered

    private void j_e_icon_modificar_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_usuariosMouseExited
        //volver al color original despues haber pasado el raton, por encima del boton de "MODIFICAR USUARIO"
        p_menu_b_modificar_usuario.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_modificar_usuariosMouseExited

    private void j_e_icon_crear_usuarios2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuarios2MouseEntered
        //// Cambio de color al hacer focus al boton "LISTA" del menu del USUARIO
        p_menu_b_lista_usuario.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_crear_usuarios2MouseEntered

    private void j_e_icon_crear_usuarios2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuarios2MouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "LISTA"
        p_menu_b_lista_usuario.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_crear_usuarios2MouseExited

    private void j_e_icon_crear_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuariosMouseClicked
        //Llamar formulario crear usuarios de sistema
        dispose();
        Crear_usuario us = new Crear_usuario();
        us.setVisible(true);
    }//GEN-LAST:event_j_e_icon_crear_usuariosMouseClicked

    private void j_e_icon_modificar_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_usuariosMouseClicked
        //Llamar formulario crear usuarios de sistema
        dispose();
        Modificar_usuarios ms = new Modificar_usuarios();
        ms.setVisible(true);
    }//GEN-LAST:event_j_e_icon_modificar_usuariosMouseClicked

    private void j_e_icon_crear_usuario_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuario_equipoMouseClicked
        //Llamar formulario crear usuarios de sistema
        dispose();
        Crear_usuario_equipo use = new Crear_usuario_equipo();
        use.setVisible(true);
    }//GEN-LAST:event_j_e_icon_crear_usuario_equipoMouseClicked

    private void j_e_icon_crear_usuarios2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_crear_usuarios2MouseClicked
        // 
        dispose();
        Listar_Usuarios lis_usuarios = new Listar_Usuarios();
        lis_usuarios.setVisible(true);
    }//GEN-LAST:event_j_e_icon_crear_usuarios2MouseClicked

    private void b_menu_administrador_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_salirMouseClicked
        //
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_b_menu_administrador_salirMouseClicked

    private void j_e_icon_registrar_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_equiposMouseClicked
        //
        dispose();
        Registrar_equipo re = new Registrar_equipo();
        re.setVisible(true);
    }//GEN-LAST:event_j_e_icon_registrar_equiposMouseClicked

    private void j_e_icon_modificar_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_equipoMouseClicked
        //
        dispose();
        Modificar_equipo me = new Modificar_equipo();
        me.setVisible(true);
    }//GEN-LAST:event_j_e_icon_modificar_equipoMouseClicked

    private void j_e_icon_registrar_tiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_tiposMouseClicked
        //
        dispose();
        Crear_tipo_equipo rte = new Crear_tipo_equipo();
        rte.setVisible(true);
    }//GEN-LAST:event_j_e_icon_registrar_tiposMouseClicked

    private void j_e_icon_lista_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipoMouseClicked
        //
        dispose();
        Listar_equipos le = new Listar_equipos();
        le.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_equipoMouseClicked

    private void j_e_icon_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_reporteMouseClicked
        //
        dispose();
        Crear_reporte cr = new Crear_reporte();
        cr.setVisible(true);
    }//GEN-LAST:event_j_e_icon_reporteMouseClicked

    private void j_e_icon_modificar_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_reporteMouseClicked
        //
        dispose();
        Modificar_reporte mr = new Modificar_reporte();
        mr.setVisible(true);
    }//GEN-LAST:event_j_e_icon_modificar_reporteMouseClicked

    private void j_e_icon_estadisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_estadisticaMouseClicked
        //
        dispose();
        Informacion in = new Informacion();
        in.setVisible(true);
    }//GEN-LAST:event_j_e_icon_estadisticaMouseClicked

    private void j_e_icon_lista_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_reporteMouseClicked
        //
        dispose();
        Listar_reportes lr = new Listar_reportes();
        lr.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_reporteMouseClicked

    private void j_e_icon_ingresar_articuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_ingresar_articuloMouseClicked
        //
        dispose();
        Crear_articulos ca = new Crear_articulos();
        ca.setVisible(true);
    }//GEN-LAST:event_j_e_icon_ingresar_articuloMouseClicked

    private void j_e_icon_modificar_articulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_articulosMouseClicked
        //
        dispose();
        Modificar_articulos ma = new Modificar_articulos();
        ma.setVisible(true);
    }//GEN-LAST:event_j_e_icon_modificar_articulosMouseClicked

    private void j_e_icon_lista_articuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_articuloMouseClicked
        //
        dispose();
        Listar_articulos la = new Listar_articulos();
        la.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_articuloMouseClicked

    private void b_menu_administrador_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_usuariosMouseClicked

        p_menuA_usuarios.setVisible(true);
        p_menuA_equipos.setVisible(false);
        p_menuA_reportes.setVisible(false);
        p_menuA_inventario.setVisible(false);

        encendido_usuario = 1;
        encendido_equipo = 0;
        encendido_reporte = 0;
        encendido_inventario = 0;

        p_menu_b_usuarios.setBackground(new Color(0, 70, 160));
        p_menu_b_equipos.setBackground(new Color(0, 102, 102));
        p_menu_b_reportes.setBackground(new Color(0, 102, 102));
        p_menu_b_inventarios.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_b_menu_administrador_usuariosMouseClicked

    private void b_menu_administrador_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_equiposMouseClicked

        p_menuA_usuarios.setVisible(false);
        p_menuA_equipos.setVisible(true);
        p_menuA_reportes.setVisible(false);
        p_menuA_inventario.setVisible(false);

        encendido_usuario = 0;
        encendido_equipo = 1;
        encendido_reporte = 0;
        encendido_inventario = 0;

        p_menu_b_usuarios.setBackground(new Color(0, 102, 102));
        p_menu_b_equipos.setBackground(new Color(0, 70, 160));
        p_menu_b_reportes.setBackground(new Color(0, 102, 102));
        p_menu_b_inventarios.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_b_menu_administrador_equiposMouseClicked

    private void b_menu_administrador_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_reportesMouseClicked

        p_menuA_usuarios.setVisible(false);
        p_menuA_equipos.setVisible(false);
        p_menuA_reportes.setVisible(true);
        p_menuA_inventario.setVisible(false);

        encendido_usuario = 0;
        encendido_equipo = 0;
        encendido_reporte = 1;
        encendido_inventario = 0;

        p_menu_b_usuarios.setBackground(new Color(0, 102, 102));
        p_menu_b_equipos.setBackground(new Color(0, 102, 102));
        p_menu_b_reportes.setBackground(new Color(0, 70, 160));
        p_menu_b_inventarios.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_b_menu_administrador_reportesMouseClicked

    private void b_menu_administrador_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_inventarioMouseClicked

        p_menuA_usuarios.setVisible(false);
        p_menuA_equipos.setVisible(false);
        p_menuA_reportes.setVisible(false);
        p_menuA_inventario.setVisible(true);

        encendido_usuario = 0;
        encendido_equipo = 0;
        encendido_reporte = 0;
        encendido_inventario = 1;

        p_menu_b_usuarios.setBackground(new Color(0, 102, 102));
        p_menu_b_equipos.setBackground(new Color(0, 102, 102));
        p_menu_b_reportes.setBackground(new Color(0, 102, 102));
        p_menu_b_inventarios.setBackground(new Color(0, 70, 160));
    }//GEN-LAST:event_b_menu_administrador_inventarioMouseClicked

    private void barra_mover2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover2MouseDragged
        //Obtener posicion x,y de la interfaz al arrastrar con el mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Posicionar la ventana segun los valores obtenidos
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_barra_mover2MouseDragged

    private void barra_mover2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover2MousePressed
        //Obtener posiciones x,y del mouse cuando se mantiene presionado
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barra_mover2MousePressed

    private void j_e_icon_registrar_equiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_equiposMouseEntered
        // Cambio de color al hacer focus al boton "Registrar" del menu del EQUIPO
        p_menu_b_registrar_equipo.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_registrar_equiposMouseEntered

    private void j_e_icon_registrar_equiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_equiposMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "REGISTRAR" del menu EQUIPO
        p_menu_b_registrar_equipo.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_registrar_equiposMouseExited

    private void j_e_icon_modificar_equipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_equipoMouseEntered
        // Cambio de color al hacer focus al boton "MODIFICAR" del menu del EQUIPO
        p_menu_b_modificar_equipo.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_modificar_equipoMouseEntered

    private void j_e_icon_modificar_equipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_equipoMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "MODIFICAR",del menu equipo
        p_menu_b_modificar_equipo.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_modificar_equipoMouseExited

    private void j_e_icon_registrar_tiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_tiposMouseEntered
        // Cambio de color al hacer focus al boton "Registrar Tipos" del menu del equipo
        p_menu_b_tipos_equipos.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_registrar_tiposMouseEntered

    private void j_e_icon_registrar_tiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_tiposMouseExited
// volver al color original despues haber pasado el raton, por encima del boton de "Registrar Tipos" del menu del equipo
        p_menu_b_tipos_equipos.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_registrar_tiposMouseExited

    private void j_e_icon_lista_equipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipoMouseEntered
        // Cambio de color al hacer focus al boton "Lista de Equipo" del menu del EQUIPO
        p_menu_b_lista_equipo.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_lista_equipoMouseEntered

    private void j_e_icon_lista_equipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipoMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "LISTA" del menu equipo
        p_menu_b_lista_equipo.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_lista_equipoMouseExited

    private void j_e_icon_reporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_reporteMouseEntered
        //  Cambio de color al hacer focus al boton "REPORTE" del menu del REPORTE
        p_menu_b_crear_reporte.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_reporteMouseEntered

    private void j_e_icon_reporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_reporteMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "REPORTE" del menu REPORTE
        p_menu_b_crear_reporte.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_reporteMouseExited

    private void j_e_icon_modificar_reporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_reporteMouseEntered
        // TODO add your handling code here:
        p_menu_b_modificar_reporte.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_modificar_reporteMouseEntered

    private void j_e_icon_modificar_reporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_reporteMouseExited
        // TODO add your handling code here:
        p_menu_b_modificar_reporte.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_modificar_reporteMouseExited

    private void j_e_icon_estadisticaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_estadisticaMouseEntered
        // TODO add your handling code here:
        p_menu_b_estadistica.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_estadisticaMouseEntered

    private void j_e_icon_estadisticaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_estadisticaMouseExited
        // TODO add your handling code here:
        p_menu_b_estadistica.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_estadisticaMouseExited

    private void j_e_icon_lista_reporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_reporteMouseEntered
        // TODO add your handling code here:
        p_menu_b_lista_reporte.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_lista_reporteMouseEntered

    private void j_e_icon_lista_reporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_reporteMouseExited
        // TODO add your handling code here:
        p_menu_b_lista_reporte.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_lista_reporteMouseExited

    private void j_e_icon_ingresar_articuloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_ingresar_articuloMouseEntered
        // TODO add your handling code here:
        p_menu_b_ingresar_articulo.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_ingresar_articuloMouseEntered

    private void j_e_icon_ingresar_articuloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_ingresar_articuloMouseExited
        // TODO add your handling code here:
        p_menu_b_ingresar_articulo.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_ingresar_articuloMouseExited

    private void j_e_icon_modificar_articulosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_articulosMouseEntered
        // TODO add your handling code here:
        p_menu_b_modificar_articulo.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_modificar_articulosMouseEntered

    private void j_e_icon_modificar_articulosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_articulosMouseExited
        // TODO add your handling code here:
        p_menu_b_modificar_articulo.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_modificar_articulosMouseExited

    private void j_e_icon_lista_articuloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_articuloMouseEntered
        // TODO add your handling code here:
        p_menu_b_lista_articulos.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_j_e_icon_lista_articuloMouseEntered

    private void j_e_icon_lista_articuloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_articuloMouseExited
        // TODO add your handling code here:
        p_menu_b_lista_articulos.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_j_e_icon_lista_articuloMouseExited

    private void btn_manualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseClicked
        open();
    }//GEN-LAST:event_btn_manualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_menu_administrador_equipos;
    private javax.swing.JLabel b_menu_administrador_inventario;
    private javax.swing.JLabel b_menu_administrador_reportes;
    private javax.swing.JLabel b_menu_administrador_salir;
    private javax.swing.JLabel b_menu_administrador_usuarios;
    private javax.swing.JLabel b_usuario_crear_evento;
    private javax.swing.JLabel b_usuario_equipo_evento;
    private javax.swing.JLabel b_usuario_lista_evento;
    private javax.swing.JLabel b_usuario_modificar_evento;
    private javax.swing.JLabel barra_mover2;
    private javax.swing.JLabel btn_manual;
    private javax.swing.JLabel e_estadistica_menu_reporte;
    private javax.swing.JLabel e_fecha;
    private javax.swing.JLabel e_hora;
    private javax.swing.JLabel e_ingresar_articulo;
    private javax.swing.JLabel e_lista_menu_equipos;
    private javax.swing.JLabel e_listar_articulo;
    private javax.swing.JLabel e_listar_reportes_menu_reporte;
    private javax.swing.JLabel e_modificar_articulo;
    private javax.swing.JLabel e_modificar_menu_equipos;
    private javax.swing.JLabel e_modificar_menu_reporte;
    private javax.swing.JLabel e_registrar_menu_equipos;
    private javax.swing.JLabel e_registro_tipo_menu_equipos;
    private javax.swing.JLabel e_reporte_menu_reporte;
    private javax.swing.JLabel i_calendario;
    private javax.swing.JLabel i_calendario_menu_equipos;
    private javax.swing.JLabel i_calendario_menu_reporte;
    private javax.swing.JLabel i_fecha;
    private javax.swing.JLabel i_hora;
    private javax.swing.JLabel i_usuario;
    private javax.swing.JLabel i_usuario_menu_equipos;
    private javax.swing.JLabel i_usuario_menu_reporte;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel j_e_icon_crear_usuario_equipo;
    private javax.swing.JLabel j_e_icon_crear_usuarios;
    private javax.swing.JLabel j_e_icon_crear_usuarios2;
    private javax.swing.JLabel j_e_icon_estadistica;
    private javax.swing.JLabel j_e_icon_ingresar_articulo;
    private javax.swing.JLabel j_e_icon_lista_articulo;
    private javax.swing.JLabel j_e_icon_lista_equipo;
    private javax.swing.JLabel j_e_icon_lista_reporte;
    private javax.swing.JLabel j_e_icon_menu_equipo;
    private javax.swing.JLabel j_e_icon_menu_inventario;
    private javax.swing.JLabel j_e_icon_menu_logo;
    private javax.swing.JLabel j_e_icon_menu_manual;
    private javax.swing.JLabel j_e_icon_menu_reporte;
    private javax.swing.JLabel j_e_icon_menu_salir;
    private javax.swing.JLabel j_e_icon_menu_usuario;
    private javax.swing.JLabel j_e_icon_modificar_articulos;
    private javax.swing.JLabel j_e_icon_modificar_equipo;
    private javax.swing.JLabel j_e_icon_modificar_reporte;
    private javax.swing.JLabel j_e_icon_modificar_usuarios;
    private javax.swing.JLabel j_e_icon_registrar_equipos;
    private javax.swing.JLabel j_e_icon_registrar_tipos;
    private javax.swing.JLabel j_e_icon_reporte;
    private javax.swing.JLabel label_equipo_nombre;
    private javax.swing.JLabel label_inventario_nombre;
    private javax.swing.JLabel label_reporte_nombre;
    private javax.swing.JLabel label_usuario_nombre;
    private prueba_diseño.PanelRound p_menuA_equipos;
    private prueba_diseño.PanelRound p_menuA_inventario;
    private prueba_diseño.PanelRound p_menuA_reportes;
    private prueba_diseño.PanelRound p_menuA_usuarios;
    private prueba_diseño.PanelRound p_menu_b_crear_reporte;
    private prueba_diseño.PanelRound p_menu_b_crear_usuario_equipo;
    private prueba_diseño.PanelRound p_menu_b_crearursuario;
    private prueba_diseño.PanelRound p_menu_b_equipos;
    private prueba_diseño.PanelRound p_menu_b_estadistica;
    private prueba_diseño.PanelRound p_menu_b_ingresar_articulo;
    private prueba_diseño.PanelRound p_menu_b_inventarios;
    private prueba_diseño.PanelRound p_menu_b_lista_articulos;
    private prueba_diseño.PanelRound p_menu_b_lista_equipo;
    private prueba_diseño.PanelRound p_menu_b_lista_reporte;
    private prueba_diseño.PanelRound p_menu_b_lista_usuario;
    private prueba_diseño.PanelRound p_menu_b_manual;
    private prueba_diseño.PanelRound p_menu_b_modificar_articulo;
    private prueba_diseño.PanelRound p_menu_b_modificar_equipo;
    private prueba_diseño.PanelRound p_menu_b_modificar_reporte;
    private prueba_diseño.PanelRound p_menu_b_modificar_usuario;
    private prueba_diseño.PanelRound p_menu_b_registrar_equipo;
    private prueba_diseño.PanelRound p_menu_b_reportes;
    private prueba_diseño.PanelRound p_menu_b_salir;
    private prueba_diseño.PanelRound p_menu_b_tipos_equipos;
    private prueba_diseño.PanelRound p_menu_b_usuarios;
    private prueba_diseño.PanelRound p_menu_barra;
    private javax.swing.JLabel r_fecha;
    private javax.swing.JLabel r_hora;
    private javax.swing.JLabel u_fecha;
    private javax.swing.JLabel u_hora;
    // End of variables declaration//GEN-END:variables

    public void open(){
        String rutaArchivoPDF = "src/manual/Manual.pdf";
        File archivoPDF = new File(rutaArchivoPDF);

        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {
            try {
                Desktop.getDesktop().open(archivoPDF);
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("El sistema operativo no admite la apertura del archivo PDF.");
        }
    }
}
