package interfaces;

import clase_base_datos.Conexion_sql;
import static interfaces.Crear_usuario.tipo;
import static interfaces.Listar_Usuarios.IDusuario_update;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Listar_reportes extends javax.swing.JFrame {

    //Variables para obtener posicion(x,y) de la ventana en la pantalla
    int mouseX, mouseY;

    public static String IDreporte_update = "";

    DefaultTableModel reporte = new DefaultTableModel();

    int num_reporte = 0;

    public Listar_reportes() {
        initComponents();
        setTitle("Listado de reportes");
        setResizable(false);
        setLocationRelativeTo(null);
        setSize(1050, 760);

        scrol_reportes.setVisible(true);


        /*Llenado de Tabla Usuarios de sistema*/
        try {
            Connection cn2 = Conexion_sql.conectar();
            PreparedStatement pst2 = cn2.prepareStatement(
                    "SELECT r.codigo_reporte, rd.tipo_reporte, r.fecha_creado_reporte,"
                    + "r.fecha_ejecucion, r.tecnico, rd.id_departamento, r.equipo,"
                    + "rd.grado_falla FROM reportes r "
                    + "INNER JOIN reporte_detallado rd ON r.codigo_reporte=rd.codigo_reporte"
                    + " ORDER BY tipo_reporte ASC");
            ResultSet rs2 = pst2.executeQuery();

            tabla_reportes = new JTable(reporte);
            scrol_reportes.setViewportView(tabla_reportes);

            reporte.addColumn("Codigo");
            reporte.addColumn("Tipo Report");
            reporte.addColumn("Fecha Regist");
            reporte.addColumn("Fecha Ejec");
            reporte.addColumn("Tecnico");
            reporte.addColumn("Depart");
            reporte.addColumn("Equipo");
            reporte.addColumn("Grado Reporte");

            while (rs2.next()) {
                Object[] filas = new Object[8];

                for (int i = 0; i < 8; i++) {
                    filas[i] = rs2.getObject(i + 1);
                }
                num_reporte++;
                reporte.addRow(filas);
            }
            cn2.close();

        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
        }

        ObtenerDatosTablaS();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound5 = new prueba_diseño.PanelRound();
        panelRound8 = new prueba_diseño.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        barra_mover4 = new javax.swing.JLabel();
        panelRound2 = new prueba_diseño.PanelRound();
        scrol_reportes = new javax.swing.JScrollPane();
        tabla_reportes = new javax.swing.JTable();
        cmb_orden = new javax.swing.JComboBox<>();
        btn_fecha = new javax.swing.JButton();
        e_tipo_reporte1 = new javax.swing.JLabel();
        annoH = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        annoD = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mesD = new javax.swing.JComboBox<>();
        diaD = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        e_tipo_reporte = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diaH = new javax.swing.JComboBox<>();
        mesH = new javax.swing.JComboBox<>();
        mes = new javax.swing.JLabel();
        e_tipo_reporte2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound8.setBackground(new java.awt.Color(36, 22, 74));
        panelRound8.setRoundBottomLeft(50);
        panelRound8.setRoundBottomRight(50);
        panelRound8.setRoundTopLeft(50);
        panelRound8.setRoundTopRight(50);
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/cerdo.png"))); // NOI18N
        panelRound8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 100));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listar Reportes");
        panelRound8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 270, 100));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/tarjeta-de-direccion (1).png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        panelRound8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 80, 60));

        panelRound5.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 800, 100));

        barra_mover4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_mover4MouseDragged(evt);
            }
        });
        barra_mover4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_mover4MousePressed(evt);
            }
        });
        panelRound5.add(barra_mover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 20));

        jPanel1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 130));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Tipo Reporte", "Fecha Registro", "Fecha Finalizacion", "Tecnico", "Departamento", "Equipo", "Grado Reporte"
            }
        ));
        scrol_reportes.setViewportView(tabla_reportes);

        panelRound2.add(scrol_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 700, 450));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 170, 750, 500));

        cmb_orden.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cmb_orden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "Tipo de reporte", "Fecha", "Tecnico", "Dpartamento", "Equipo" }));
        cmb_orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ordenActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 180, 40));

        btn_fecha.setBackground(new java.awt.Color(38, 22, 74));
        btn_fecha.setForeground(new java.awt.Color(255, 255, 255));
        btn_fecha.setText("Filtrar por Fecha");
        btn_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, 160, 30));

        e_tipo_reporte1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        e_tipo_reporte1.setForeground(new java.awt.Color(255, 255, 255));
        e_tipo_reporte1.setText("Ordenar por");
        jPanel1.add(e_tipo_reporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 200, -1));

        annoH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        jPanel1.add(annoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, 70, 30));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("año");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, -1, -1));

        annoD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        jPanel1.add(annoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 70, 30));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("año");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("mes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, -1, -1));

        mesD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(mesD, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, 50, 30));

        diaD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(diaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 50, 30));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("dia");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, -1, -1));

        e_tipo_reporte.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        e_tipo_reporte.setForeground(new java.awt.Color(255, 255, 255));
        e_tipo_reporte.setText("Hasta:");
        jPanel1.add(e_tipo_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 70, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("dia");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, -1, -1));

        diaH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(diaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 50, 30));

        mesH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(mesH, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 50, 30));

        mes.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        mes.setForeground(new java.awt.Color(255, 255, 255));
        mes.setText("mes");
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, -1, -1));

        e_tipo_reporte2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        e_tipo_reporte2.setForeground(new java.awt.Color(255, 255, 255));
        e_tipo_reporte2.setText("Desde:");
        jPanel1.add(e_tipo_reporte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        //Boton
        //Salir de la interface
        if (tipo.equals("Administrador")) {
            dispose();
            Administrador menu = new Administrador();
            menu.setVisible(true);

        } else if (tipo.equals("Tecnico")) {
            dispose();
            Tecnico menu = new Tecnico();
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error del servidor");
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void barra_mover4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover4MouseDragged
        //Obtener posicion x,y de la interfaz al arrastrar con el mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Posicionar la ventana segun los valores obtenidos
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_barra_mover4MouseDragged

    private void barra_mover4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover4MousePressed
        //Obtener posiciones x,y del mouse cuando se mantiene presionado
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barra_mover4MousePressed

    private void cmb_ordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ordenActionPerformed
        if (cmb_orden.getSelectedIndex() == 0) {

            diaD.setSelectedIndex(0);
            mesD.setSelectedIndex(0);
            annoD.setSelectedIndex(0);

            diaH.setSelectedIndex(0);
            mesH.setSelectedIndex(0);
            annoH.setSelectedIndex(0);

        } else if (cmb_orden.getSelectedIndex() == 1) {

            diaD.setSelectedIndex(0);
            mesD.setSelectedIndex(0);
            annoD.setSelectedIndex(0);

            diaH.setSelectedIndex(0);
            mesH.setSelectedIndex(0);
            annoH.setSelectedIndex(0);

            reporte.setRowCount(0);
            reporte.setColumnCount(0);

            /*Llenado de Tabla Usuarios de sistema*/
            try {
                Connection cn2 = Conexion_sql.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "SELECT r.codigo_reporte, rd.tipo_reporte, r.fecha_creado_reporte,"
                        + "r.fecha_ejecucion, r.tecnico, rd.id_departamento, r.equipo,"
                        + "rd.grado_falla FROM reportes r "
                        + "INNER JOIN reporte_detallado rd ON r.codigo_reporte=rd.codigo_reporte"
                        + " ORDER BY tipo_reporte ASC");
                ResultSet rs2 = pst2.executeQuery();

                tabla_reportes = new JTable(reporte);
                scrol_reportes.setViewportView(tabla_reportes);

                reporte.addColumn("Codigo");
                reporte.addColumn("Tipo Report");
                reporte.addColumn("Fecha Regist");
                reporte.addColumn("Fecha Ejec");
                reporte.addColumn("Tecnico");
                reporte.addColumn("Depart");
                reporte.addColumn("Equipo");
                reporte.addColumn("Grado Reporte");

                while (rs2.next()) {
                    Object[] filas = new Object[8];

                    for (int i = 0; i < 8; i++) {
                        filas[i] = rs2.getObject(i + 1);
                    }
                    num_reporte++;
                    reporte.addRow(filas);
                }
                cn2.close();

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
            }

        } else if (cmb_orden.getSelectedIndex() == 2) {

            diaD.setSelectedIndex(0);
            mesD.setSelectedIndex(0);
            annoD.setSelectedIndex(0);

            diaH.setSelectedIndex(0);
            mesH.setSelectedIndex(0);
            annoH.setSelectedIndex(0);

            reporte.setRowCount(0);
            reporte.setColumnCount(0);


            /*Llenado de Tabla Usuarios de sistema*/
            try {
                Connection cn2 = Conexion_sql.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "SELECT r.codigo_reporte, rd.tipo_reporte, r.fecha_creado_reporte,"
                        + "r.fecha_ejecucion, r.tecnico, rd.id_departamento, r.equipo,"
                        + "rd.grado_falla FROM reportes r "
                        + "INNER JOIN reporte_detallado rd ON r.codigo_reporte=rd.codigo_reporte"
                        + " ORDER BY fecha_creado_reporte ASC");
                ResultSet rs2 = pst2.executeQuery();

                tabla_reportes = new JTable(reporte);
                scrol_reportes.setViewportView(tabla_reportes);

                reporte.addColumn("Codigo");
                reporte.addColumn("Tipo Report");
                reporte.addColumn("Fecha Regist");
                reporte.addColumn("Fecha Ejec");
                reporte.addColumn("Tecnico");
                reporte.addColumn("Depart");
                reporte.addColumn("Equipo");
                reporte.addColumn("Grado Reporte");

                while (rs2.next()) {
                    Object[] filas = new Object[8];

                    for (int i = 0; i < 8; i++) {
                        filas[i] = rs2.getObject(i + 1);
                    }
                    num_reporte++;
                    reporte.addRow(filas);
                }
                cn2.close();

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
            }

        } else if (cmb_orden.getSelectedIndex() == 3) {

            diaD.setSelectedIndex(0);
            mesD.setSelectedIndex(0);
            annoD.setSelectedIndex(0);

            diaH.setSelectedIndex(0);
            mesH.setSelectedIndex(0);
            annoH.setSelectedIndex(0);

            reporte.setRowCount(0);
            reporte.setColumnCount(0);

            /*Llenado de Tabla Usuarios de sistema*/
            try {
                Connection cn2 = Conexion_sql.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "SELECT r.codigo_reporte, rd.tipo_reporte, r.fecha_creado_reporte,"
                        + "r.fecha_ejecucion, r.tecnico, rd.id_departamento, r.equipo,"
                        + "rd.grado_falla FROM reportes r "
                        + "INNER JOIN reporte_detallado rd ON r.codigo_reporte=rd.codigo_reporte"
                        + " ORDER BY tecnico ASC");
                ResultSet rs2 = pst2.executeQuery();

                tabla_reportes = new JTable(reporte);
                scrol_reportes.setViewportView(tabla_reportes);

                reporte.addColumn("Codigo");
                reporte.addColumn("Tipo Report");
                reporte.addColumn("Fecha Regist");
                reporte.addColumn("Fecha Ejec");
                reporte.addColumn("Tecnico");
                reporte.addColumn("Depart");
                reporte.addColumn("Equipo");
                reporte.addColumn("Grado Reporte");

                while (rs2.next()) {
                    Object[] filas = new Object[8];

                    for (int i = 0; i < 8; i++) {
                        filas[i] = rs2.getObject(i + 1);
                    }
                    num_reporte++;
                    reporte.addRow(filas);
                }
                cn2.close();

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
            }

        } else if (cmb_orden.getSelectedIndex() == 4) {

            diaD.setSelectedIndex(0);
            mesD.setSelectedIndex(0);
            annoD.setSelectedIndex(0);

            diaH.setSelectedIndex(0);
            mesH.setSelectedIndex(0);
            annoH.setSelectedIndex(0);

            reporte.setRowCount(0);
            reporte.setColumnCount(0);

            /*Llenado de Tabla Usuarios de sistema*/
            try {
                Connection cn2 = Conexion_sql.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "SELECT r.codigo_reporte, rd.tipo_reporte, r.fecha_creado_reporte,"
                        + "r.fecha_ejecucion, r.tecnico, rd.id_departamento, r.equipo,"
                        + "rd.grado_falla FROM reportes r "
                        + "INNER JOIN reporte_detallado rd ON r.codigo_reporte=rd.codigo_reporte"
                        + " ORDER BY id_departamento ASC");
                ResultSet rs2 = pst2.executeQuery();

                tabla_reportes = new JTable(reporte);
                scrol_reportes.setViewportView(tabla_reportes);

                reporte.addColumn("Codigo");
                reporte.addColumn("Tipo Report");
                reporte.addColumn("Fecha Regist");
                reporte.addColumn("Fecha Ejec");
                reporte.addColumn("Tecnico");
                reporte.addColumn("Depart");
                reporte.addColumn("Equipo");
                reporte.addColumn("Grado Reporte");

                while (rs2.next()) {
                    Object[] filas = new Object[8];

                    for (int i = 0; i < 8; i++) {
                        filas[i] = rs2.getObject(i + 1);
                    }
                    num_reporte++;
                    reporte.addRow(filas);
                }
                cn2.close();

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
            }

        } else if (cmb_orden.getSelectedIndex() == 5) {

            diaD.setSelectedIndex(0);
            mesD.setSelectedIndex(0);
            annoD.setSelectedIndex(0);

            diaH.setSelectedIndex(0);
            mesH.setSelectedIndex(0);
            annoH.setSelectedIndex(0);

            reporte.setRowCount(0);
            reporte.setColumnCount(0);


            /*Llenado de Tabla Usuarios de sistema*/
            try {
                Connection cn2 = Conexion_sql.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "SELECT r.codigo_reporte, rd.tipo_reporte, r.fecha_creado_reporte,"
                        + "r.fecha_ejecucion, r.tecnico, rd.id_departamento, r.equipo,"
                        + "rd.grado_falla FROM reportes r "
                        + "INNER JOIN reporte_detallado rd ON r.codigo_reporte=rd.codigo_reporte"
                        + " ORDER BY equipo ASC");
                ResultSet rs2 = pst2.executeQuery();

                tabla_reportes = new JTable(reporte);
                scrol_reportes.setViewportView(tabla_reportes);

                reporte.addColumn("Codigo");
                reporte.addColumn("Tipo Report");
                reporte.addColumn("Fecha Regist");
                reporte.addColumn("Fecha Ejec");
                reporte.addColumn("Tecnico");
                reporte.addColumn("Depart");
                reporte.addColumn("Equipo");
                reporte.addColumn("Grado Reporte");

                while (rs2.next()) {
                    Object[] filas = new Object[8];

                    for (int i = 0; i < 8; i++) {
                        filas[i] = rs2.getObject(i + 1);
                    }
                    num_reporte++;
                    reporte.addRow(filas);
                }
                cn2.close();

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
            }
        }
    }//GEN-LAST:event_cmb_ordenActionPerformed

    private void btn_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechaActionPerformed

        String desde = annoD.getSelectedItem() + "-" + mesD.getSelectedItem() + "-" + diaD.getSelectedItem();
        String hasta = annoH.getSelectedItem() + "-" + mesH.getSelectedItem() + "-" + diaH.getSelectedItem();

        reporte.setRowCount(0);
        reporte.setColumnCount(0);

        /*Llenado de Tabla Usuarios de sistema*/
        String consulta = "SELECT r.codigo_reporte, r.fecha_creado_reporte, r.fecha_ejecucion, "
                + "r.tecnico, r.equipo, d.grado_falla, d.id_departamento, d.tipo_reporte "
                + "FROM reportes r JOIN reporte_detallado d ON r.codigo_reporte = d.codigo_reporte "
                + "WHERE r.fecha_creado_reporte BETWEEN '" + desde + "' AND '" + hasta + "'"
                + "ORDER BY r.fecha_creado_reporte ASC";

        try {
            Connection cn2 = Conexion_sql.conectar();
            PreparedStatement pst2 = cn2.prepareStatement(consulta);
            ResultSet rs2 = pst2.executeQuery();

            tabla_reportes = new JTable(reporte);
            scrol_reportes.setViewportView(tabla_reportes);

            reporte.addColumn("Codigo");
            reporte.addColumn("Tipo Report");
            reporte.addColumn("Fecha Regist");
            reporte.addColumn("Fecha Ejec");
            reporte.addColumn("Tecnico");
            reporte.addColumn("Depart");
            reporte.addColumn("Equipo");
            reporte.addColumn("Grado Reporte");

            while (rs2.next()) {
                Object[] filas = new Object[8];

                for (int i = 0; i < 8; i++) {
                    filas[i] = rs2.getObject(i + 1);
                }
                num_reporte++;
                reporte.addRow(filas);
            }
            cn2.close();

        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
        }
    }//GEN-LAST:event_btn_fechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar_reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> annoD;
    private javax.swing.JComboBox<String> annoH;
    private javax.swing.JLabel barra_mover4;
    private javax.swing.JButton btn_fecha;
    private javax.swing.JComboBox<String> cmb_orden;
    private javax.swing.JComboBox<String> diaD;
    private javax.swing.JComboBox<String> diaH;
    private javax.swing.JLabel e_tipo_reporte;
    private javax.swing.JLabel e_tipo_reporte1;
    private javax.swing.JLabel e_tipo_reporte2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mes;
    private javax.swing.JComboBox<String> mesD;
    private javax.swing.JComboBox<String> mesH;
    private prueba_diseño.PanelRound panelRound2;
    private prueba_diseño.PanelRound panelRound5;
    private prueba_diseño.PanelRound panelRound8;
    private javax.swing.JScrollPane scrol_reportes;
    private javax.swing.JTable tabla_reportes;
    // End of variables declaration//GEN-END:variables

    public void ObtenerDatosTablaS() {
        tabla_reportes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = tabla_reportes.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    IDreporte_update = (String) reporte.getValueAt(fila_point, columna_point);
                    Modificar_reporte info = new Modificar_reporte();
                    info.setVisible(true);
                    dispose();
                }
            }
        });
    }

}
