package interfaces;

import clase_base_datos.Conexion_sql;
import funcionabilidad.ValidacionesGenerales;
import funcionabilidad.ValidacionesIndividual;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public static String nombre_apellido;
    public static String tipo_permiso;
    public static String usuario_nombre;

    //Variables para obtener posicion(x,y) de la ventana en la pantalla
    int mouseX, mouseY;

    public Login() {
        initComponents();
        setTitle("Inicio de sesion");
        setSize(600, 650);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelRound1 = new prueba_diseño.PanelRound();
        t_login_contraseña = new javax.swing.JPasswordField();
        panelRound2 = new prueba_diseño.PanelRound();
        t_login_usuario = new javax.swing.JTextField();
        panelRound3 = new prueba_diseño.PanelRound();
        b_login_ingresar = new javax.swing.JLabel();
        e_login_icon_inicio = new javax.swing.JLabel();
        panelRound4 = new prueba_diseño.PanelRound();
        e_login_usuario = new javax.swing.JLabel();
        panelRound5 = new prueba_diseño.PanelRound();
        e_login_contraseña = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        barra_mover = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 22, 74));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inicio de Sesión");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 310, -1));

        panelRound1.setBackground(new java.awt.Color(0, 102, 102));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_login_contraseña.setBackground(new java.awt.Color(0, 102, 102));
        t_login_contraseña.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        t_login_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        t_login_contraseña.setBorder(null);
        panelRound1.add(t_login_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 280, 35));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 300, 40));

        panelRound2.setBackground(new java.awt.Color(0, 102, 102));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_login_usuario.setBackground(new java.awt.Color(0, 102, 102));
        t_login_usuario.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        t_login_usuario.setForeground(new java.awt.Color(255, 255, 255));
        t_login_usuario.setBorder(null);
        panelRound2.add(t_login_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 280, 35));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 300, 40));

        panelRound3.setBackground(new java.awt.Color(0, 102, 102));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_login_ingresar.setBackground(new java.awt.Color(0, 102, 102));
        b_login_ingresar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        b_login_ingresar.setForeground(new java.awt.Color(234, 234, 234));
        b_login_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_login_ingresar.setText("   Ingresar");
        b_login_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_ingresarMouseClicked(evt);
            }
        });
        panelRound3.add(b_login_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        e_login_icon_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_login_icon_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/tarjeta-de-direccion (1).png"))); // NOI18N
        panelRound3.add(e_login_icon_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 160, 50));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(60);
        panelRound4.setRoundBottomRight(60);
        panelRound4.setRoundTopLeft(60);
        panelRound4.setRoundTopRight(60);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_login_usuario.setBackground(new java.awt.Color(255, 255, 255));
        e_login_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_login_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/usuario (3).png"))); // NOI18N
        panelRound4.add(e_login_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 40, 40));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(60);
        panelRound5.setRoundBottomRight(60);
        panelRound5.setRoundTopLeft(60);
        panelRound5.setRoundTopRight(60);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_login_contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_login_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/cerrar.png"))); // NOI18N
        e_login_contraseña.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound5.add(e_login_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 40, 40));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/computadora (1).png"))); // NOI18N
        jLabel4.setText("Sistema Interno para Control Operacional de Tecnología");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 380, 50));

        barra_mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_moverMouseDragged(evt);
            }
        });
        barra_mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_moverMousePressed(evt);
            }
        });
        jPanel1.add(barra_mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        salir.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_login_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_ingresarMouseClicked

        nombre_apellido = "";
        usuario_nombre = "";
        tipo_permiso = "";

        //obtener datos de campos de texto de la interface
        String nombre_usuario = t_login_usuario.getText().trim();
        String contraseña_usuario = t_login_contraseña.getText().trim();
        String[] campos = {nombre_usuario, contraseña_usuario};

        //Consulta a la base de datos
        String sql = "select nombre, apellido, nombre_usuario, contraseña, permiso, estado from usuarios_sistema"
                + " where nombre_usuario = '" + nombre_usuario
                + "' and contraseña = '" + contraseña_usuario + "'";

        //clases de validacion de datos
        ValidacionesGenerales validarG = new ValidacionesGenerales();
        ValidacionesIndividual validarI = new ValidacionesIndividual();

        //Validacion de campos vacios
        if (validarG.camposVaciosArray(campos) == true) {

            //Consulta de base de datos
            try {
                Connection cn = Conexion_sql.conectar();
                PreparedStatement pst = cn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();

                //Comprobar existencia del ususrio en la base de datos
                if (rs.next()) {
                    String nombre = rs.getString("nombre");
                    String apellido = rs.getString("apellido");
                    String nombreUsuario = rs.getString("nombre_usuario");
                    String contraseña = rs.getString("contraseña");
                    String permiso = rs.getString("permiso");
                    String estado = rs.getString("estado");

                    //Verificar que coincidan los datos con los de la base de datos
                    if (validarI.compararDatos(nombre_usuario, contraseña_usuario, nombreUsuario, contraseña)) {
                        nombre_apellido = nombre + " " + apellido;
                        usuario_nombre = nombreUsuario;
                        tipo_permiso = permiso;

                        //clases de interfaces Administrador - Tecnico
                        Administrador admin = new Administrador();
                        Tecnico tec = new Tecnico();

                        if (estado.equals("Activo")) {

                            if (permiso.equals("Administrador")) {
                                admin.setVisible(true);
                                dispose();
                            } else if (permiso.equals("Tecnico")) {
                                tec.setVisible(true);
                                dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "El tipo de usuario no se encontro en la base de datos");
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "El Usuario ingresado se encuentra inactivo");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecto");
                    }
                } else {
                    System.out.println("Usuario no existe");
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecta");
                }
            } catch (Exception e) {
                System.err.println("Error en la consulta del ususrio del sistemas" + e);
            }

        } else {
            System.out.println("Vacio");
        }
    }//GEN-LAST:event_b_login_ingresarMouseClicked

    private void barra_moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_moverMouseDragged
        //Obtener posicion x,y de la interfaz al arrastrar con el mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Posicionar la ventana segun los valores obtenidos
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_barra_moverMouseDragged

    private void barra_moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_moverMousePressed
        //Obtener posiciones x,y del mouse cuando se mantiene presionado
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barra_moverMousePressed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        //Salir del sistema
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        //
        salir.setForeground(Color.red);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        //
        salir.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_login_ingresar;
    private javax.swing.JLabel barra_mover;
    private javax.swing.JLabel e_login_contraseña;
    private javax.swing.JLabel e_login_icon_inicio;
    private javax.swing.JLabel e_login_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private prueba_diseño.PanelRound panelRound1;
    private prueba_diseño.PanelRound panelRound2;
    private prueba_diseño.PanelRound panelRound3;
    private prueba_diseño.PanelRound panelRound4;
    private prueba_diseño.PanelRound panelRound5;
    private javax.swing.JLabel salir;
    private javax.swing.JPasswordField t_login_contraseña;
    private javax.swing.JTextField t_login_usuario;
    // End of variables declaration//GEN-END:variables
}
