package interfaces;

import clase_base_datos.Conexion_sql;
import funcionabilidad.ValidacionesGenerales;
import funcionabilidad.ValidacionesIndividual;
import static interfaces.Crear_usuario.tipo;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Registrar_equipo extends javax.swing.JFrame {

    //Variables para obtener posicion(x,y) de la ventana en la pantalla
    int mouseX, mouseY;

    public Registrar_equipo() {
        initComponents();
        setSize(500, 770);
        setTitle("Registrar Equipos");
        setLocationRelativeTo(null);
        setResizable(false);

        try {
            Connection cn = Conexion_sql.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT nombre_tipo_equipo FROM `tipo_equipo`");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                cmb_tipo.addItem(rs.getString("nombre_tipo_equipo"));

            }
            cn.close();

        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
        }

        try {
            Connection cn = Conexion_sql.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT nombre_departamento FROM `departamentos` ORDER BY nombre_departamento");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                cmb_departamento.addItem(rs.getString("nombre_departamento"));

            }
            cn.close();

        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
        }

        try {
            Connection cn = Conexion_sql.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT cedula FROM `usuarios_equipos` ORDER BY cedula");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                cmb_usuario.addItem(rs.getString("cedula"));

            }
            cn.close();

        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        panelRound10 = new prueba_diseño.PanelRound();
        panelRound8 = new prueba_diseño.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound1 = new prueba_diseño.PanelRound();
        salir = new javax.swing.JLabel();
        p_rgistro_equipo_nombre = new prueba_diseño.PanelRound();
        txt_nombre = new javax.swing.JTextField();
        p_rgistro_equipo_modelo = new prueba_diseño.PanelRound();
        txt_modelo = new javax.swing.JTextField();
        p_rgistro_equipo_Marca = new prueba_diseño.PanelRound();
        txt_marca = new javax.swing.JTextField();
        p_rgistro_equipo_sistema_operativo = new prueba_diseño.PanelRound();
        txt_so = new javax.swing.JTextField();
        p_equipo_registrar_equipo = new prueba_diseño.PanelRound();
        b_registrar = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        cmb_estado = new javax.swing.JComboBox<>();
        cmb_departamento = new javax.swing.JComboBox<>();
        cmb_usuario = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        barra_mover4 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound10.setBackground(new java.awt.Color(0, 102, 102));
        panelRound10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound8.setBackground(new java.awt.Color(36, 22, 74));
        panelRound8.setRoundBottomLeft(50);
        panelRound8.setRoundBottomRight(50);
        panelRound8.setRoundTopLeft(50);
        panelRound8.setRoundTopRight(50);
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/cerdo.png"))); // NOI18N
        panelRound8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 90));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de Equipo");
        panelRound8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 220, 70));

        panelRound1.setBackground(new java.awt.Color(36, 22, 74));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/tarjeta-de-direccion (1).png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        panelRound1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        panelRound8.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 50, 40));

        panelRound10.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 80));

        p_rgistro_equipo_nombre.setRoundBottomLeft(50);
        p_rgistro_equipo_nombre.setRoundBottomRight(50);
        p_rgistro_equipo_nombre.setRoundTopLeft(50);
        p_rgistro_equipo_nombre.setRoundTopRight(50);
        p_rgistro_equipo_nombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.setBackground(new java.awt.Color(218, 215, 220));
        txt_nombre.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        p_rgistro_equipo_nombre.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 160, 40));

        panelRound10.add(p_rgistro_equipo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 50));

        p_rgistro_equipo_modelo.setRoundBottomLeft(50);
        p_rgistro_equipo_modelo.setRoundBottomRight(50);
        p_rgistro_equipo_modelo.setRoundTopLeft(50);
        p_rgistro_equipo_modelo.setRoundTopRight(50);
        p_rgistro_equipo_modelo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_modelo.setBackground(new java.awt.Color(218, 215, 220));
        txt_modelo.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modelo.setBorder(null);
        p_rgistro_equipo_modelo.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 160, 40));

        panelRound10.add(p_rgistro_equipo_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 180, 50));

        p_rgistro_equipo_Marca.setRoundBottomLeft(50);
        p_rgistro_equipo_Marca.setRoundBottomRight(50);
        p_rgistro_equipo_Marca.setRoundTopLeft(50);
        p_rgistro_equipo_Marca.setRoundTopRight(50);
        p_rgistro_equipo_Marca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_marca.setBackground(new java.awt.Color(218, 215, 220));
        txt_marca.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txt_marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_marca.setBorder(null);
        p_rgistro_equipo_Marca.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 160, 40));

        panelRound10.add(p_rgistro_equipo_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 180, 50));

        p_rgistro_equipo_sistema_operativo.setRoundBottomLeft(50);
        p_rgistro_equipo_sistema_operativo.setRoundBottomRight(50);
        p_rgistro_equipo_sistema_operativo.setRoundTopLeft(50);
        p_rgistro_equipo_sistema_operativo.setRoundTopRight(50);
        p_rgistro_equipo_sistema_operativo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_so.setBackground(new java.awt.Color(218, 215, 220));
        txt_so.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txt_so.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_so.setBorder(null);
        p_rgistro_equipo_sistema_operativo.add(txt_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 160, 40));

        panelRound10.add(p_rgistro_equipo_sistema_operativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 180, 50));

        p_equipo_registrar_equipo.setBackground(new java.awt.Color(36, 22, 74));
        p_equipo_registrar_equipo.setRoundBottomLeft(50);
        p_equipo_registrar_equipo.setRoundBottomRight(50);
        p_equipo_registrar_equipo.setRoundTopLeft(50);
        p_equipo_registrar_equipo.setRoundTopRight(50);
        p_equipo_registrar_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_registrar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        b_registrar.setForeground(new java.awt.Color(255, 255, 255));
        b_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_registrar.setText("Registrar");
        b_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_registrarMouseExited(evt);
            }
        });
        p_equipo_registrar_equipo.add(b_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        panelRound10.add(p_equipo_registrar_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 180, 50));

        cmb_tipo.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cmb_tipo.setForeground(new java.awt.Color(36, 22, 74));
        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------" }));
        cmb_tipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });
        panelRound10.add(cmb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 40));

        cmb_estado.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cmb_estado.setForeground(new java.awt.Color(36, 22, 74));
        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "En revision", "En uso", "almacen", "En desuso" }));
        cmb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estadoActionPerformed(evt);
            }
        });
        panelRound10.add(cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, 40));

        cmb_departamento.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cmb_departamento.setForeground(new java.awt.Color(36, 22, 74));
        cmb_departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------" }));
        cmb_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_departamentoActionPerformed(evt);
            }
        });
        panelRound10.add(cmb_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 170, 40));

        cmb_usuario.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cmb_usuario.setForeground(new java.awt.Color(36, 22, 74));
        cmb_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------" }));
        cmb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_usuarioActionPerformed(evt);
            }
        });
        panelRound10.add(cmb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 180, 40));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modelo ");
        panelRound10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 160, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estado");
        panelRound10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 140, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre de equipo");
        panelRound10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sistema operativo");
        panelRound10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 160, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Marca");
        panelRound10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 80, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Usuario");
        panelRound10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 140, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo");
        panelRound10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Departamento");
        panelRound10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 140, -1));

        barra_mover4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_mover4MouseDragged(evt);
            }
        });
        barra_mover4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_mover4MousePressed(evt);
            }
        });
        panelRound10.add(barra_mover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 20));

        getContentPane().add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void cmb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_usuarioActionPerformed

    private void cmb_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_departamentoActionPerformed

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoActionPerformed

    private void cmb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estadoActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        //Boton
        //Salir de la interface
        if (tipo.equals("Administrador")) {
            dispose();
            Administrador menu = new Administrador();
            menu.setVisible(true);

        } else if (tipo.equals("Tecnico")) {
            dispose();
            Tecnico menu = new Tecnico();
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error del servidor");
        }
    }//GEN-LAST:event_salirMouseClicked

    private void barra_mover4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover4MouseDragged
        //Obtener posicion x,y de la interfaz al arrastrar con el mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Posicionar la ventana segun los valores obtenidos
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_barra_mover4MouseDragged

    private void barra_mover4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover4MousePressed
        //Obtener posiciones x,y del mouse cuando se mantiene presionado
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barra_mover4MousePressed

    private void b_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_registrarMouseEntered
        //Cambiar el color al pasar el mouse por encima del boton "Registrar", del modulo
        // "Registrar equipo", 
        p_equipo_registrar_equipo.setBackground(new Color(20, 22, 84));
    }//GEN-LAST:event_b_registrarMouseEntered

    private void b_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_registrarMouseExited
        // Volver al color orginal , cuando el mouse no este sobre el boton "Registrar", de
        //Modulo "Registrar equipo"
        p_equipo_registrar_equipo.setBackground(new Color(36, 22, 74));
    }//GEN-LAST:event_b_registrarMouseExited

    private void b_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_registrarMouseClicked
        //Registrar Usuario y guardar en la base de datos

        //Llamado de clases
        ValidacionesGenerales vg = new ValidacionesGenerales();
        ValidacionesIndividual vi = new ValidacionesIndividual();

        //Obtener datos de los campos de textos
        String modelo = txt_modelo.getText().trim();
        String nombre = txt_nombre.getText().trim();
        String marca = txt_marca.getText().trim();
        String so = txt_so.getText().trim();
        String departamento = (String) cmb_departamento.getSelectedItem();
        String usuario = (String) cmb_usuario.getSelectedItem();
        String tipoE = (String) cmb_tipo.getSelectedItem();
        String estado = (String) cmb_estado.getSelectedItem();

        //Arreglos para validar los datos
        String[] camposT = {nombre, departamento, usuario, tipoE, estado};
        String[] camposL = {tipoE, estado};
        String[] camposN = {usuario};
        String[] camposA = {nombre, modelo, marca};

        //Consultas
        String comprobacion = "SELECT nombre_equipo FROM equipos "
                + "WHERE nombre_equipo ='" + nombre + "'";
        String agregar = "INSERT INTO equipos values (?,?,?,?,?,?,?,?,?,?)";

        //Validacion de campos vacios
        if (vg.camposVaciosArray(camposT)) {

            //Validacion de los diferentes caracteres de los campos
            if (!vg.validarLetras(camposL)) {
                JOptionPane.showMessageDialog(null, "Los campos (nombre, tipo, estado) solo deben contener letras...");
            } else if (!vg.validarNumerosC(camposN)) {
                JOptionPane.showMessageDialog(null, "El campo (usuario) solo deben contener Numeros...");
            } else if (!vg.validarTodos(camposA)) {
                JOptionPane.showMessageDialog(null, "Los campos (departamento, modelo, marca) debe contener solo guiones...");
            } else {

                //Verificaion de ecistencia de usuario
                try {
                    Connection cn = Conexion_sql.conectar();
                    PreparedStatement pst = cn.prepareStatement(comprobacion);
                    ResultSet rs = pst.executeQuery();

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Usuario ya existe...");
                    } else if (!rs.next()) {

                        //Registrar usuario
                        try {
                            Connection cn2 = Conexion_sql.conectar();
                            PreparedStatement pst2 = cn.prepareStatement(agregar);

                            pst2.setString(1, null);
                            pst2.setString(2, nombre);
                            pst2.setString(3, marca);
                            pst2.setString(4, so);
                            pst2.setString(5, null);
                            pst2.setString(6, estado);
                            pst2.setString(7, Administrador.usuario);
                            pst2.setString(8, departamento);
                            pst2.setString(9, usuario);
                            pst2.setString(10, tipoE);
                            pst2.executeUpdate();

                            JOptionPane.showMessageDialog(null, "Equipo Registrado con exito...");

                            cn2.close();
                            cn.close();

                            if (tipo.equals("Administrador")) {
                                dispose();
                                Administrador menu = new Administrador();
                                menu.setVisible(true);

                            } else if (tipo.equals("Tecnico")) {
                                dispose();
                                Tecnico menu = new Tecnico();
                                menu.setVisible(true);
                            } else {
                                JOptionPane.showMessageDialog(null, "Error del servidor");
                            }

//                        
                        } catch (Exception e) {
                            System.err.println(e);
                            JOptionPane.showMessageDialog(null, "Error al registrar equipo...");
                        }

                    }
                } catch (Exception e) {
                    System.err.println(e);
                    JOptionPane.showMessageDialog(null, "Error al verificar equipo");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hay campos vacios...");
        }
    }//GEN-LAST:event_b_registrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_registrar;
    private javax.swing.JLabel barra_mover4;
    private javax.swing.JComboBox<String> cmb_departamento;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JComboBox<String> cmb_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private prueba_diseño.PanelRound p_equipo_registrar_equipo;
    private prueba_diseño.PanelRound p_rgistro_equipo_Marca;
    private prueba_diseño.PanelRound p_rgistro_equipo_modelo;
    private prueba_diseño.PanelRound p_rgistro_equipo_nombre;
    private prueba_diseño.PanelRound p_rgistro_equipo_sistema_operativo;
    private prueba_diseño.PanelRound panelRound1;
    private prueba_diseño.PanelRound panelRound10;
    private prueba_diseño.PanelRound panelRound8;
    private javax.swing.JLabel salir;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_so;
    // End of variables declaration//GEN-END:variables
}
