/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;

/**
 *
 * @author g.torrealba
 */
public class Tecnico extends javax.swing.JFrame {

    //Encendido de color de los botones del menu principal
    int encendido_equipo = 1;
    int encendido_reporte = 0;
    int encendido_inventario = 0;
    
    //Variables estaticas que pasan entre interfaces
    public static String tipo = Login.tipo_permiso;
    public static String nombre = Login.nombre_apellido;
    public static String usuario = Login.usuario_nombre;
    
    
    /*Fecha y Hora*/
    LocalDateTime fecha = LocalDateTime.now();

    int annio = fecha.getYear();
    int mes = fecha.getMonthValue();
    int dia = fecha.getDayOfMonth();
    int hora = fecha.getHour();
    int minutos = fecha.getMinute();
    int segundo = fecha.getSecond();
    
    
    
    //Variables para obtener posicion(x,y) de la ventana en la pantalla
    int mouseX, mouseY;
    
    public Tecnico() {
        
        //configuracion de la ventana
        initComponents();
        setTitle("Menu Tecnico");
        setSize(900, 720);
        setLocationRelativeTo(null);
        setResizable(false);
        
        //configuracion de los elementos del panel
        
        label_equipo_nombre.setText(Administrador.nombreA);
        label_reporte_nombre.setText(Administrador.nombreA);
        label_inventario_nombre.setText(Administrador.nombreA);
        
        
        p_menuA_equipos.setVisible(true);
        p_menuA_reportes.setVisible(false);
        p_menuA_inventario.setVisible(false);
        
        //Hora y Fecha de la interfaz
        e_fecha.setText(dia + " / " + mes + " / " + annio);
        e_hora.setText(hora + ":" + minutos + "PM");
        
        r_fecha.setText(dia + " / " + mes + " / " + annio);
        r_hora.setText(hora + ":" + minutos + "PM");
        
        i_fecha.setText(dia + " / " + mes + " / " + annio);
        i_hora.setText(hora + ":" + minutos + "PM");

        p_menu_b_equipos.setBackground(new Color(0, 70, 160));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_menu_barra = new prueba_diseño.PanelRound();
        p_menu_b_equipos = new prueba_diseño.PanelRound();
        b_menu_administrador_equipos = new javax.swing.JLabel();
        j_e_icon_menu_equipo = new javax.swing.JLabel();
        p_menu_b_reportes = new prueba_diseño.PanelRound();
        j_e_icon_menu_reporte = new javax.swing.JLabel();
        b_menu_administrador_reportes = new javax.swing.JLabel();
        p_menu_b_inventarios = new prueba_diseño.PanelRound();
        j_e_icon_menu_inventario = new javax.swing.JLabel();
        b_menu_administrador_inventario = new javax.swing.JLabel();
        p_menu_b_manual = new prueba_diseño.PanelRound();
        btn_manual = new javax.swing.JLabel();
        j_e_icon_menu_manual = new javax.swing.JLabel();
        p_menu_b_salir = new prueba_diseño.PanelRound();
        b_menu_administrador_salir = new javax.swing.JLabel();
        j_e_icon_menu_salir = new javax.swing.JLabel();
        j_e_icon_menu_logo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        p_menuA_inventario = new prueba_diseño.PanelRound();
        p_menu_b_registrar_equipo2 = new prueba_diseño.PanelRound();
        j_e_icon_registrar_equipos2 = new javax.swing.JLabel();
        p_menu_b_modificar_equipo2 = new prueba_diseño.PanelRound();
        j_e_icon_modificar_equipo2 = new javax.swing.JLabel();
        p_menu_b_lista_equipo2 = new prueba_diseño.PanelRound();
        j_e_icon_lista_equipo4 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        i_fecha = new javax.swing.JLabel();
        i_hora = new javax.swing.JLabel();
        label_inventario_nombre = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        b_equipos_registro2 = new javax.swing.JLabel();
        p_menuA_reportes = new prueba_diseño.PanelRound();
        p_menu_b_registrar_equipo1 = new prueba_diseño.PanelRound();
        j_e_icon_registrar_equipos1 = new javax.swing.JLabel();
        p_menu_b_modificar_equipo1 = new prueba_diseño.PanelRound();
        j_e_icon_modificar_equipo1 = new javax.swing.JLabel();
        p_menu_b_tipos_equipos1 = new prueba_diseño.PanelRound();
        j_e_icon_lista_equipo2 = new javax.swing.JLabel();
        p_menu_b_lista_equipo1 = new prueba_diseño.PanelRound();
        j_e_icon_lista_equipo3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        r_fecha = new javax.swing.JLabel();
        r_hora = new javax.swing.JLabel();
        label_reporte_nombre = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        b_equipos_registro1 = new javax.swing.JLabel();
        b_equipos_modiicar1 = new javax.swing.JLabel();
        b_equipos_lista1 = new javax.swing.JLabel();
        b_equipos_tipos1 = new javax.swing.JLabel();
        p_menuA_equipos = new prueba_diseño.PanelRound();
        p_menu_b_registrar_equipo = new prueba_diseño.PanelRound();
        j_e_icon_registrar_equipos = new javax.swing.JLabel();
        p_menu_b_modificar_equipo = new prueba_diseño.PanelRound();
        j_e_icon_modificar_equipo = new javax.swing.JLabel();
        p_menu_b_tipos_equipos = new prueba_diseño.PanelRound();
        j_e_icon_lista_equipo1 = new javax.swing.JLabel();
        p_menu_b_lista_equipo = new prueba_diseño.PanelRound();
        j_e_icon_lista_equipo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        e_fecha = new javax.swing.JLabel();
        e_hora = new javax.swing.JLabel();
        label_equipo_nombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        b_equipos_registro = new javax.swing.JLabel();
        b_equipos_modiicar = new javax.swing.JLabel();
        b_equipos_lista = new javax.swing.JLabel();
        b_equipos_tipos = new javax.swing.JLabel();
        barra_mover2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_barra.setBackground(new java.awt.Color(36, 22, 74));
        p_menu_barra.setRoundBottomLeft(50);
        p_menu_barra.setRoundBottomRight(50);
        p_menu_barra.setRoundTopLeft(50);
        p_menu_barra.setRoundTopRight(50);
        p_menu_barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_b_equipos.setBackground(new java.awt.Color(0, 102, 102));
        p_menu_b_equipos.setRoundBottomLeft(50);
        p_menu_b_equipos.setRoundBottomRight(50);
        p_menu_b_equipos.setRoundTopLeft(50);
        p_menu_b_equipos.setRoundTopRight(50);
        p_menu_b_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_menu_b_equiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_menu_b_equiposMouseExited(evt);
            }
        });
        p_menu_b_equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_menu_administrador_equipos.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_menu_administrador_equipos.setForeground(new java.awt.Color(234, 234, 234));
        b_menu_administrador_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_equipos.setText("EQUIPOS");
        b_menu_administrador_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_equiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_equiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_equiposMouseExited(evt);
            }
        });
        p_menu_b_equipos.add(b_menu_administrador_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        j_e_icon_menu_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/equipo-de-computadora (1).png"))); // NOI18N
        p_menu_b_equipos.add(j_e_icon_menu_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 40, 40));

        p_menu_barra.add(p_menu_b_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 50));

        p_menu_b_reportes.setBackground(new java.awt.Color(0, 102, 102));
        p_menu_b_reportes.setRoundBottomLeft(50);
        p_menu_b_reportes.setRoundBottomRight(50);
        p_menu_b_reportes.setRoundTopLeft(50);
        p_menu_b_reportes.setRoundTopRight(50);
        p_menu_b_reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_menu_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/portapapeles.png"))); // NOI18N
        p_menu_b_reportes.add(j_e_icon_menu_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 40));

        b_menu_administrador_reportes.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_menu_administrador_reportes.setForeground(new java.awt.Color(234, 234, 234));
        b_menu_administrador_reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_reportes.setText("REPORTES");
        b_menu_administrador_reportes.setPreferredSize(new java.awt.Dimension(54, 17));
        b_menu_administrador_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_reportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_reportesMouseExited(evt);
            }
        });
        p_menu_b_reportes.add(b_menu_administrador_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        p_menu_barra.add(p_menu_b_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 50));

        p_menu_b_inventarios.setBackground(new java.awt.Color(0, 102, 102));
        p_menu_b_inventarios.setRoundBottomLeft(50);
        p_menu_b_inventarios.setRoundBottomRight(50);
        p_menu_b_inventarios.setRoundTopLeft(50);
        p_menu_b_inventarios.setRoundTopRight(50);
        p_menu_b_inventarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_menu_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/caja.png"))); // NOI18N
        p_menu_b_inventarios.add(j_e_icon_menu_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 40));

        b_menu_administrador_inventario.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        b_menu_administrador_inventario.setForeground(new java.awt.Color(234, 234, 234));
        b_menu_administrador_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_inventario.setText("   INVENTARIO");
        b_menu_administrador_inventario.setPreferredSize(new java.awt.Dimension(54, 17));
        b_menu_administrador_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_inventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_inventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_inventarioMouseExited(evt);
            }
        });
        p_menu_b_inventarios.add(b_menu_administrador_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        p_menu_barra.add(p_menu_b_inventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 180, 50));

        p_menu_b_manual.setRoundBottomLeft(50);
        p_menu_b_manual.setRoundBottomRight(50);
        p_menu_b_manual.setRoundTopLeft(50);
        p_menu_b_manual.setRoundTopRight(50);
        p_menu_b_manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_menu_b_manualMouseClicked(evt);
            }
        });
        p_menu_b_manual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_manual.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        btn_manual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_manual.setText(" MANUAL");
        btn_manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_manualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_manualMouseExited(evt);
            }
        });
        p_menu_b_manual.add(btn_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        j_e_icon_menu_manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/instrucciones.png"))); // NOI18N
        p_menu_b_manual.add(j_e_icon_menu_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        p_menu_barra.add(p_menu_b_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 140, 50));

        p_menu_b_salir.setRoundBottomLeft(50);
        p_menu_b_salir.setRoundBottomRight(50);
        p_menu_b_salir.setRoundTopLeft(50);
        p_menu_b_salir.setRoundTopRight(50);
        p_menu_b_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_menu_administrador_salir.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        b_menu_administrador_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_menu_administrador_salir.setText("   SALIR");
        b_menu_administrador_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menu_administrador_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_menu_administrador_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_menu_administrador_salirMouseExited(evt);
            }
        });
        p_menu_b_salir.add(b_menu_administrador_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        j_e_icon_menu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/salida.png"))); // NOI18N
        p_menu_b_salir.add(j_e_icon_menu_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        p_menu_barra.add(p_menu_b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 120, 50));

        j_e_icon_menu_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_menu_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menuA/cerdo.png"))); // NOI18N
        p_menu_barra.add(j_e_icon_menu_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 70));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sicot");
        p_menu_barra.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 60));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Técnico");
        p_menu_barra.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 30));

        jPanel1.add(p_menu_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 650));

        p_menuA_inventario.setBackground(new java.awt.Color(234, 234, 234));
        p_menuA_inventario.setRoundBottomLeft(50);
        p_menuA_inventario.setRoundBottomRight(50);
        p_menuA_inventario.setRoundTopLeft(50);
        p_menuA_inventario.setRoundTopRight(50);
        p_menuA_inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_b_registrar_equipo2.setRoundBottomLeft(50);
        p_menu_b_registrar_equipo2.setRoundBottomRight(50);
        p_menu_b_registrar_equipo2.setRoundTopLeft(50);
        p_menu_b_registrar_equipo2.setRoundTopRight(50);
        p_menu_b_registrar_equipo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_registrar_equipos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_registrar_equipos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/inventario.png"))); // NOI18N
        j_e_icon_registrar_equipos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_equipos2MouseClicked(evt);
            }
        });
        p_menu_b_registrar_equipo2.add(j_e_icon_registrar_equipos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_inventario.add(p_menu_b_registrar_equipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 170));

        p_menu_b_modificar_equipo2.setRoundBottomLeft(50);
        p_menu_b_modificar_equipo2.setRoundBottomRight(50);
        p_menu_b_modificar_equipo2.setRoundTopLeft(50);
        p_menu_b_modificar_equipo2.setRoundTopRight(50);
        p_menu_b_modificar_equipo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_modificar_equipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_modificar_equipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/la-gestion-del-inventario.png"))); // NOI18N
        j_e_icon_modificar_equipo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_equipo2MouseClicked(evt);
            }
        });
        p_menu_b_modificar_equipo2.add(j_e_icon_modificar_equipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_inventario.add(p_menu_b_modificar_equipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 170, 170));

        p_menu_b_lista_equipo2.setRoundBottomLeft(50);
        p_menu_b_lista_equipo2.setRoundBottomRight(50);
        p_menu_b_lista_equipo2.setRoundTopLeft(50);
        p_menu_b_lista_equipo2.setRoundTopRight(50);
        p_menu_b_lista_equipo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_equipo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_equipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/inventario (1).png"))); // NOI18N
        j_e_icon_lista_equipo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipo4MouseClicked(evt);
            }
        });
        p_menu_b_lista_equipo2.add(j_e_icon_lista_equipo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_inventario.add(p_menu_b_lista_equipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, 170));

        jLabel45.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Listar Artículos");
        p_menuA_inventario.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 170, -1));

        jLabel46.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Modificar Artículo");
        p_menuA_inventario.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 170, -1));

        jLabel47.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Ingresar Artículo");
        p_menuA_inventario.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, -1));

        i_fecha.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        i_fecha.setText("00/00/0000");
        p_menuA_inventario.add(i_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, 80, -1));

        i_hora.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        i_hora.setText("00:00 APM");
        p_menuA_inventario.add(i_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, -1));

        label_inventario_nombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        label_inventario_nombre.setText("Clarelvis Leal");
        p_menuA_inventario.add(label_inventario_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, -1));

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/picpersonas-llenas.png"))); // NOI18N
        p_menuA_inventario.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 40));

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario-reloj (2).png"))); // NOI18N
        p_menuA_inventario.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 9, 40, 40));
        p_menuA_inventario.add(b_equipos_registro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 170));

        jPanel1.add(p_menuA_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        p_menuA_reportes.setBackground(new java.awt.Color(234, 234, 234));
        p_menuA_reportes.setRoundBottomLeft(50);
        p_menuA_reportes.setRoundBottomRight(50);
        p_menuA_reportes.setRoundTopLeft(50);
        p_menuA_reportes.setRoundTopRight(50);
        p_menuA_reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_b_registrar_equipo1.setRoundBottomLeft(50);
        p_menu_b_registrar_equipo1.setRoundBottomRight(50);
        p_menu_b_registrar_equipo1.setRoundTopLeft(50);
        p_menu_b_registrar_equipo1.setRoundTopRight(50);
        p_menu_b_registrar_equipo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_registrar_equipos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_registrar_equipos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/formulario-de-llenado.png"))); // NOI18N
        j_e_icon_registrar_equipos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_equipos1MouseClicked(evt);
            }
        });
        p_menu_b_registrar_equipo1.add(j_e_icon_registrar_equipos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_registrar_equipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 170));

        p_menu_b_modificar_equipo1.setRoundBottomLeft(50);
        p_menu_b_modificar_equipo1.setRoundBottomRight(50);
        p_menu_b_modificar_equipo1.setRoundTopLeft(50);
        p_menu_b_modificar_equipo1.setRoundTopRight(50);
        p_menu_b_modificar_equipo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_modificar_equipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_modificar_equipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/eliminar.png"))); // NOI18N
        j_e_icon_modificar_equipo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_equipo1MouseClicked(evt);
            }
        });
        p_menu_b_modificar_equipo1.add(j_e_icon_modificar_equipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_modificar_equipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 170, 170));

        p_menu_b_tipos_equipos1.setRoundBottomLeft(50);
        p_menu_b_tipos_equipos1.setRoundBottomRight(50);
        p_menu_b_tipos_equipos1.setRoundTopLeft(50);
        p_menu_b_tipos_equipos1.setRoundTopRight(50);
        p_menu_b_tipos_equipos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_equipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_equipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/grafico-de-barras.png"))); // NOI18N
        j_e_icon_lista_equipo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipo2MouseClicked(evt);
            }
        });
        p_menu_b_tipos_equipos1.add(j_e_icon_lista_equipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_tipos_equipos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 170));

        p_menu_b_lista_equipo1.setRoundBottomLeft(50);
        p_menu_b_lista_equipo1.setRoundBottomRight(50);
        p_menu_b_lista_equipo1.setRoundTopLeft(50);
        p_menu_b_lista_equipo1.setRoundTopRight(50);
        p_menu_b_lista_equipo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_equipo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_equipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/gestion-de-proyectos.png"))); // NOI18N
        j_e_icon_lista_equipo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipo3MouseClicked(evt);
            }
        });
        p_menu_b_lista_equipo1.add(j_e_icon_lista_equipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_reportes.add(p_menu_b_lista_equipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 170, 170));

        jLabel28.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Lista");
        p_menuA_reportes.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 170, -1));

        jLabel29.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Modificar");
        p_menuA_reportes.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 170, -1));

        jLabel30.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Reporte ");
        p_menuA_reportes.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, -1));

        r_fecha.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        r_fecha.setText("00/00/0000");
        p_menuA_reportes.add(r_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, 80, -1));

        r_hora.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        r_hora.setText("00:00 APM");
        p_menuA_reportes.add(r_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, -1));

        label_reporte_nombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        label_reporte_nombre.setText("Clarelvis Leal");
        p_menuA_reportes.add(label_reporte_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, -1));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/picpersonas-llenas.png"))); // NOI18N
        p_menuA_reportes.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 40));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario-reloj (2).png"))); // NOI18N
        p_menuA_reportes.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 9, 40, 40));

        jLabel36.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Estadísticas");
        p_menuA_reportes.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 170, -1));
        p_menuA_reportes.add(b_equipos_registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 210));
        p_menuA_reportes.add(b_equipos_modiicar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 180, 210));
        p_menuA_reportes.add(b_equipos_lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, 200));
        p_menuA_reportes.add(b_equipos_tipos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 200));

        jPanel1.add(p_menuA_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        p_menuA_equipos.setBackground(new java.awt.Color(234, 234, 234));
        p_menuA_equipos.setRoundBottomLeft(50);
        p_menuA_equipos.setRoundBottomRight(50);
        p_menuA_equipos.setRoundTopLeft(50);
        p_menuA_equipos.setRoundTopRight(50);
        p_menuA_equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_menu_b_registrar_equipo.setRoundBottomLeft(50);
        p_menu_b_registrar_equipo.setRoundBottomRight(50);
        p_menu_b_registrar_equipo.setRoundTopLeft(50);
        p_menu_b_registrar_equipo.setRoundTopRight(50);
        p_menu_b_registrar_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_registrar_equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_registrar_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/agregar.png"))); // NOI18N
        j_e_icon_registrar_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_registrar_equiposMouseClicked(evt);
            }
        });
        p_menu_b_registrar_equipo.add(j_e_icon_registrar_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_registrar_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 170));

        p_menu_b_modificar_equipo.setRoundBottomLeft(50);
        p_menu_b_modificar_equipo.setRoundBottomRight(50);
        p_menu_b_modificar_equipo.setRoundTopLeft(50);
        p_menu_b_modificar_equipo.setRoundTopRight(50);
        p_menu_b_modificar_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_modificar_equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_modificar_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/configuracion.png"))); // NOI18N
        j_e_icon_modificar_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_modificar_equipoMouseClicked(evt);
            }
        });
        p_menu_b_modificar_equipo.add(j_e_icon_modificar_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_modificar_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 90, 170, 170));

        p_menu_b_tipos_equipos.setRoundBottomLeft(50);
        p_menu_b_tipos_equipos.setRoundBottomRight(50);
        p_menu_b_tipos_equipos.setRoundTopLeft(50);
        p_menu_b_tipos_equipos.setRoundTopRight(50);
        p_menu_b_tipos_equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_equipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_equipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu_equipos/nube (3).png"))); // NOI18N
        j_e_icon_lista_equipo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipo1MouseClicked(evt);
            }
        });
        p_menu_b_tipos_equipos.add(j_e_icon_lista_equipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_tipos_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 170));

        p_menu_b_lista_equipo.setRoundBottomLeft(50);
        p_menu_b_lista_equipo.setRoundBottomRight(50);
        p_menu_b_lista_equipo.setRoundTopLeft(50);
        p_menu_b_lista_equipo.setRoundTopRight(50);
        p_menu_b_lista_equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_e_icon_lista_equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_e_icon_lista_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/computadora-personal.png"))); // NOI18N
        j_e_icon_lista_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_e_icon_lista_equipoMouseClicked(evt);
            }
        });
        p_menu_b_lista_equipo.add(j_e_icon_lista_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        p_menuA_equipos.add(p_menu_b_lista_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, 170));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Lista");
        p_menuA_equipos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 170, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Modificar");
        p_menuA_equipos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 170, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Registrar ");
        p_menuA_equipos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, -1));

        e_fecha.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        e_fecha.setText("00/00/0000");
        p_menuA_equipos.add(e_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, 80, -1));

        e_hora.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        e_hora.setText("00:00 APM");
        p_menuA_equipos.add(e_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, -1));

        label_equipo_nombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        label_equipo_nombre.setText("Clarelvis Leal");
        p_menuA_equipos.add(label_equipo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/picpersonas-llenas.png"))); // NOI18N
        p_menuA_equipos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario-reloj (2).png"))); // NOI18N
        p_menuA_equipos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 9, 40, 40));

        jLabel25.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Registrar tipos");
        p_menuA_equipos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 170, -1));
        p_menuA_equipos.add(b_equipos_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 210));
        p_menuA_equipos.add(b_equipos_modiicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 180, 210));
        p_menuA_equipos.add(b_equipos_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, 200));
        p_menuA_equipos.add(b_equipos_tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 200));

        jPanel1.add(p_menuA_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        barra_mover2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_mover2MouseDragged(evt);
            }
        });
        barra_mover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_mover2MousePressed(evt);
            }
        });
        jPanel1.add(barra_mover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_menu_administrador_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_equiposMouseClicked

        p_menuA_equipos.setVisible(true);
        p_menuA_reportes.setVisible(false);
        p_menuA_inventario.setVisible(false);

        encendido_equipo = 1;
        encendido_reporte = 0;
        encendido_inventario = 0;

        p_menu_b_equipos.setBackground(new Color(0, 70, 160));
        p_menu_b_reportes.setBackground(new Color(0, 102, 102));
        p_menu_b_inventarios.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_b_menu_administrador_equiposMouseClicked

    private void b_menu_administrador_equiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_equiposMouseEntered
        // Cambio de color al hacer focus al boton "EQUIPO" del menu del adminitrador
        if (encendido_equipo == 0) {
            p_menu_b_equipos.setBackground(new Color(0, 65, 75));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_equiposMouseEntered

    private void b_menu_administrador_equiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_equiposMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "EQUIPO"
        if (encendido_equipo == 0) {
            p_menu_b_equipos.setBackground(new Color(0, 102, 102));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_equiposMouseExited

    private void p_menu_b_equiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_menu_b_equiposMouseEntered

    }//GEN-LAST:event_p_menu_b_equiposMouseEntered

    private void p_menu_b_equiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_menu_b_equiposMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_menu_b_equiposMouseExited

    private void b_menu_administrador_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_reportesMouseClicked

        p_menuA_equipos.setVisible(false);
        p_menuA_reportes.setVisible(true);
        p_menuA_inventario.setVisible(false);

        encendido_equipo = 0;
        encendido_reporte = 1;
        encendido_inventario = 0;

        p_menu_b_equipos.setBackground(new Color(0, 102, 102));
        p_menu_b_reportes.setBackground(new Color(0, 70, 160));
        p_menu_b_inventarios.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_b_menu_administrador_reportesMouseClicked

    private void b_menu_administrador_reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_reportesMouseEntered
        // Cambio de color al hacer focus al boton "REPORTE" del menu del adminitrador
        if (encendido_reporte == 0) {
            p_menu_b_reportes.setBackground(new Color(0, 65, 75));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_reportesMouseEntered

    private void b_menu_administrador_reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_reportesMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "REPORTE"
        if (encendido_reporte == 0) {
            p_menu_b_reportes.setBackground(new Color(0, 102, 102));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_reportesMouseExited

    private void b_menu_administrador_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_inventarioMouseClicked

        p_menuA_equipos.setVisible(false);
        p_menuA_reportes.setVisible(false);
        p_menuA_inventario.setVisible(true);

        encendido_equipo = 0;
        encendido_reporte = 0;
        encendido_inventario = 1;

        p_menu_b_equipos.setBackground(new Color(0, 102, 102));
        p_menu_b_reportes.setBackground(new Color(0, 102, 102));
        p_menu_b_inventarios.setBackground(new Color(0, 70, 160));
    }//GEN-LAST:event_b_menu_administrador_inventarioMouseClicked

    private void b_menu_administrador_inventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_inventarioMouseEntered
        // Cambio de color al hacer focus al boton "INVENTARIO" del menu del adminitrador
        if (encendido_inventario == 0) {
            p_menu_b_inventarios.setBackground(new Color(0, 65, 75));
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_inventarioMouseEntered

    private void b_menu_administrador_inventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_inventarioMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "INVENTRIO"
        if (encendido_inventario == 0) {
            p_menu_b_inventarios.setBackground(new Color(0, 102, 102));;
        } else {
        }
    }//GEN-LAST:event_b_menu_administrador_inventarioMouseExited

    private void btn_manualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseEntered
        // Cambio de color al hacer focus al boton "MANUAL" del menu del adminitrador
        p_menu_b_manual.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_btn_manualMouseEntered

    private void btn_manualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "MANUAL"
        p_menu_b_manual.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_btn_manualMouseExited

    private void p_menu_b_manualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_menu_b_manualMouseClicked

    }//GEN-LAST:event_p_menu_b_manualMouseClicked

    private void b_menu_administrador_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_salirMouseClicked
        //
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_b_menu_administrador_salirMouseClicked

    private void b_menu_administrador_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_salirMouseEntered
        // Cambio de color al hacer focus al boton "SALIR" del menu del adminitrador
        p_menu_b_salir.setBackground(new Color(250, 250, 250));
    }//GEN-LAST:event_b_menu_administrador_salirMouseEntered

    private void b_menu_administrador_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menu_administrador_salirMouseExited
        // volver al color original despues haber pasado el raton, por encima del boton de "SALIR"
        p_menu_b_salir.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_b_menu_administrador_salirMouseExited

    private void j_e_icon_registrar_equipos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_equipos2MouseClicked
        //
        dispose();
        Crear_articulos ca = new Crear_articulos();
        ca.setVisible(true);
    }//GEN-LAST:event_j_e_icon_registrar_equipos2MouseClicked

    private void j_e_icon_modificar_equipo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_equipo2MouseClicked
        //
        dispose();
        Modificar_articulos ma = new Modificar_articulos();
        ma.setVisible(true);
    }//GEN-LAST:event_j_e_icon_modificar_equipo2MouseClicked

    private void j_e_icon_lista_equipo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipo4MouseClicked
        //
        dispose();
        Listar_articulos la = new Listar_articulos();
        la.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_equipo4MouseClicked

    private void j_e_icon_registrar_equipos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_equipos1MouseClicked
        //
        dispose();
        Crear_reporte cr = new Crear_reporte();
        cr.setVisible(true);
    }//GEN-LAST:event_j_e_icon_registrar_equipos1MouseClicked

    private void j_e_icon_modificar_equipo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_equipo1MouseClicked
        //
        dispose();
        Modificar_reporte mr = new Modificar_reporte();
        mr.setVisible(true);
    }//GEN-LAST:event_j_e_icon_modificar_equipo1MouseClicked

    private void j_e_icon_lista_equipo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipo2MouseClicked
        //
        dispose();
        Informacion in = new Informacion();
        in.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_equipo2MouseClicked

    private void j_e_icon_lista_equipo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipo3MouseClicked
        //
        dispose();
        Listar_reportes lr = new Listar_reportes();
        lr.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_equipo3MouseClicked

    private void j_e_icon_registrar_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_registrar_equiposMouseClicked
        //
        dispose();
        Registrar_equipo re = new Registrar_equipo();
        re.setVisible(true);
    }//GEN-LAST:event_j_e_icon_registrar_equiposMouseClicked

    private void j_e_icon_modificar_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_modificar_equipoMouseClicked
        //
        dispose();
        Modificar_equipo me = new Modificar_equipo();
        me.setVisible(true);
    }//GEN-LAST:event_j_e_icon_modificar_equipoMouseClicked

    private void j_e_icon_lista_equipo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipo1MouseClicked
        //
        dispose();
        Crear_tipo_equipo rte = new Crear_tipo_equipo();
        rte.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_equipo1MouseClicked

    private void j_e_icon_lista_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_e_icon_lista_equipoMouseClicked
        //
        dispose();
        Listar_equipos le = new Listar_equipos();
        le.setVisible(true);
    }//GEN-LAST:event_j_e_icon_lista_equipoMouseClicked

    private void barra_mover2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover2MouseDragged
        //Obtener posicion x,y de la interfaz al arrastrar con el mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Posicionar la ventana segun los valores obtenidos
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_barra_mover2MouseDragged

    private void barra_mover2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_mover2MousePressed
        //Obtener posiciones x,y del mouse cuando se mantiene presionado
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barra_mover2MousePressed

    private void btn_manualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manualMouseClicked
        //Llamar metodo que abre el pdf del manual en pantalla
        open();
    }//GEN-LAST:event_btn_manualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_equipos_lista;
    private javax.swing.JLabel b_equipos_lista1;
    private javax.swing.JLabel b_equipos_modiicar;
    private javax.swing.JLabel b_equipos_modiicar1;
    private javax.swing.JLabel b_equipos_registro;
    private javax.swing.JLabel b_equipos_registro1;
    private javax.swing.JLabel b_equipos_registro2;
    private javax.swing.JLabel b_equipos_tipos;
    private javax.swing.JLabel b_equipos_tipos1;
    private javax.swing.JLabel b_menu_administrador_equipos;
    private javax.swing.JLabel b_menu_administrador_inventario;
    private javax.swing.JLabel b_menu_administrador_reportes;
    private javax.swing.JLabel b_menu_administrador_salir;
    private javax.swing.JLabel barra_mover2;
    private javax.swing.JLabel btn_manual;
    private javax.swing.JLabel e_fecha;
    private javax.swing.JLabel e_hora;
    private javax.swing.JLabel i_fecha;
    private javax.swing.JLabel i_hora;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel j_e_icon_lista_equipo;
    private javax.swing.JLabel j_e_icon_lista_equipo1;
    private javax.swing.JLabel j_e_icon_lista_equipo2;
    private javax.swing.JLabel j_e_icon_lista_equipo3;
    private javax.swing.JLabel j_e_icon_lista_equipo4;
    private javax.swing.JLabel j_e_icon_menu_equipo;
    private javax.swing.JLabel j_e_icon_menu_inventario;
    private javax.swing.JLabel j_e_icon_menu_logo;
    private javax.swing.JLabel j_e_icon_menu_manual;
    private javax.swing.JLabel j_e_icon_menu_reporte;
    private javax.swing.JLabel j_e_icon_menu_salir;
    private javax.swing.JLabel j_e_icon_modificar_equipo;
    private javax.swing.JLabel j_e_icon_modificar_equipo1;
    private javax.swing.JLabel j_e_icon_modificar_equipo2;
    private javax.swing.JLabel j_e_icon_registrar_equipos;
    private javax.swing.JLabel j_e_icon_registrar_equipos1;
    private javax.swing.JLabel j_e_icon_registrar_equipos2;
    private javax.swing.JLabel label_equipo_nombre;
    private javax.swing.JLabel label_inventario_nombre;
    private javax.swing.JLabel label_reporte_nombre;
    private prueba_diseño.PanelRound p_menuA_equipos;
    private prueba_diseño.PanelRound p_menuA_inventario;
    private prueba_diseño.PanelRound p_menuA_reportes;
    private prueba_diseño.PanelRound p_menu_b_equipos;
    private prueba_diseño.PanelRound p_menu_b_inventarios;
    private prueba_diseño.PanelRound p_menu_b_lista_equipo;
    private prueba_diseño.PanelRound p_menu_b_lista_equipo1;
    private prueba_diseño.PanelRound p_menu_b_lista_equipo2;
    private prueba_diseño.PanelRound p_menu_b_manual;
    private prueba_diseño.PanelRound p_menu_b_modificar_equipo;
    private prueba_diseño.PanelRound p_menu_b_modificar_equipo1;
    private prueba_diseño.PanelRound p_menu_b_modificar_equipo2;
    private prueba_diseño.PanelRound p_menu_b_registrar_equipo;
    private prueba_diseño.PanelRound p_menu_b_registrar_equipo1;
    private prueba_diseño.PanelRound p_menu_b_registrar_equipo2;
    private prueba_diseño.PanelRound p_menu_b_reportes;
    private prueba_diseño.PanelRound p_menu_b_salir;
    private prueba_diseño.PanelRound p_menu_b_tipos_equipos;
    private prueba_diseño.PanelRound p_menu_b_tipos_equipos1;
    private prueba_diseño.PanelRound p_menu_barra;
    private javax.swing.JLabel r_fecha;
    private javax.swing.JLabel r_hora;
    // End of variables declaration//GEN-END:variables


    public void open(){
        String rutaArchivoPDF = "src/manual/Manual.pdf";
        File archivoPDF = new File(rutaArchivoPDF);

        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {
            try {
                Desktop.getDesktop().open(archivoPDF);
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("El sistema operativo no admite la apertura del archivo PDF.");
        }
    }
}
